### ISSUE TITLE
TFS Upgrade breaks this

### ISSUE THREAD

**Issue by kasajian** [Microsoft/tfs-cli#105]
Every time we get a new TFS update from Microsoft, this breaks.   

Someone has to remember to go back to IIS on the TFS server to enable basic-authentication.

Is there some way that this can be fixed so upgrade TFS doesn't break this awesome tool?

**Comment by trevorsg** [comment]
Thanks for the feedback. I agree, and I've talked to the folks who own Upgrade, and unfortunately it's not something they can do at the moment. I will be adding NTLM support soon - hopefully that eliminates your need to use basic authentication.
