### ISSUE TITLE
could not determine content type for extension .js

### ISSUE THREAD

**Issue by ankitgo** [Microsoft/tfs-cli#108]
Hi I get the below warning when I build my vsix.
How do i override this?
warning : Could not determine content type for extension .js. Defaulting to application/octet-stream. To override this, add a contentType property to this file entry in the manifest.

**Comment by trevorsg** [comment]
Do you have the latest version? Try running `npm up -g tfx-cli`.

**Comment by ankitgo** [comment]
@trevorsg  how do i override this warning?

**Comment by trevorsg** [comment]
You shouldn't get this warning if you are using the latest version of tfx-cli. There are two ways to override it though. First is to open regedit and ensure there is a key for HKCR\.js\Content Type set to a string value of "application/javascript". The second option is to add "contentType": "application/javascript" to the file entry in your manifest, as mentioned in the warning message.
