### ISSUE TITLE
tfx login won't accept a Personal Access Token

### ISSUE THREAD

**Issue by danatcofo** [Microsoft/tfs-cli#109]
After calling `tfx login --service-url https://app.market.visualstudio.com` it asks for a Personal access token. I can't do anything but press `enter` key at this prompt.  It won't accept any characters nor will it accept the paste command from the window tools `Edit/Paste`

Installation was via `npm install -g tfx-cli` inside a Windows 10 command prompt with Node 4.4.3 LTS installed

was able to login via `tfx login --service-url https://app.market.visualstudio.com --token ***********` however.

**Comment by trevorsg** [comment]
This is as designed. The token prompt is treated as a password prompt, so even though text is being input, it does not get echoed back to the user.

**Comment by danatcofo** [comment]
really.... So the user has no indication that anything is happening or being accepted.  How is that not a bug.  If nothing else its extremely ui unfriendly and contributes to confusion.

**Comment by bryanmacfarlane** [comment]
> It won't accept any characters nor will it accept the paste command from the window tools  Edit/Paste 

You should be able to paste.  At least I'm able to.  For PAT tokens, it's only realistic to paste.  Paste didn't work?  Trevor, can you repro that?

**Comment by trevorsg** [comment]
Yeah, I understand the confusion. However, this is a pretty common way to accept secret information (such as passwords) at a terminal or command prompt. We could probably make it print asterisks.

@bryanmacfarlane Paste works fine - it just doesn't echo anything back to the user.

**Comment by danatcofo** [comment]
Spent about an hour trying to figure out how to get it to work before finally giving up and looking for an argument token for the pat in the source. I think echoing asterisks would be a wonderful solution to prevent the confusion.

a repository search for --service-url turned up the --token argument so I could actually get working.

By the way I don't see --token documented in any .md files but I could of simply missed it.

Thanks for the responding @trevorsg & @bryanmacfarlane

**Comment by trevorsg** [comment]
The --token argument is shown when you use --help, e.g. `tfx login --help`.
