### ISSUE TITLE
Add support for creating service endpoints

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/tfs-cli#113]
It looks like vsts-node-api supports [creating service endpoints](https://github.com/Microsoft/vsts-node-api/blob/master/api/CoreApi.ts#L90) but tfs-cli doesn't expose this functionality.

![image](https://cloud.githubusercontent.com/assets/4112046/14895374/e3e0c6e2-0d3d-11e6-86b8-d4716c4b1f47.png)

**Comment by trevorsg** [comment]
The tfs-cli is not necessarily a fully-fledged command line application for interacting with VSTS REST APIs. This is out of scope for us at the moment.
