### ISSUE TITLE
Publishing build Tasks to VSTS

### ISSUE THREAD

**Issue by IsmaelKP** [Microsoft/tfs-cli#115]
I am trying to publish tasks on VSTS . 
I have been able to upload them successfully. If I try to reupload them I have a Error which tell me that the Extension has already been Created.
But... 
When going to the portal I am unable to see the tasks in build and Release tasks.
When trying to List the tasks _"tfx build tasks list"_ I don't have any trace of the tasks I uploaded.

**Comment by trevorsg** [comment]
@bryanmacfarlane Can you take a look?

**Comment by bryanmacfarlane** [comment]
Specifically, which tasks are you uploading?

**Comment by IsmaelKP** [comment]
I was trying to implement Docker and Chef. I found the issue. Scripts were having a "Preview" mention which made them invisible to the task Menu. I close the issue.
