### ISSUE TITLE
tfx extension create --manifest-globs vss-extension.json -> Error: Missing element text

### ISSUE THREAD

**Issue by SimoneGatti** [Microsoft/tfs-cli#122]
Hi all!

I tried to create a custom build task for Visual Studio Team Services, but when I try to compile my extension appear only an Error whitout meaning.
Please, can you help me to understand this error?

Thank you!

![schermata 2016-05-24 alle 10 30 29](https://cloud.githubusercontent.com/assets/16915705/15497344/9b382784-219a-11e6-8739-106126b116df.png)

**Comment by SimoneGatti** [comment]
Better messages could be appreciated.

**Comment by ericmattingly** [comment]
How did you fix this? I am having the same issues and cant seem to nail it down even with the traces

**Comment by SimoneGatti** [comment]
I forgot to add files array in extension manifest. Without it the extension doesn't know where are the tasks. In my example "Task1" is the name of the folder containing the files of my task:

<pre>"files": [
      {
        "path": "Task1"
      }
    ],
</pre>

I find this project: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
 where you can find many example of extension.
I tried to package locally ScriptShell example and to install it in my VSTS, but it still doesn't work. Why? Isn't it the original extension code? I missed a passage?
In the agent installed on my server I compare original ScriptShell task with my ScriptShell task: the result is that in original ScriptShell task folder there is a node_module folder containing all the library used by typescript code, but In my task folder not.
