### ISSUE TITLE
tfx sends incorrect host header

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/tfs-cli#123]
When tfx is executed against a non-default http port, the port number is included in the host header. This is a HTTP protocol violation:

![image](https://cloud.githubusercontent.com/assets/4173387/15704918/112007ca-27ed-11e6-89a2-87523e7afe24.png)

```
GET /tfs/_apis/gallery/publishers/jessehouwing/extensions/jessehouwing-vsts-variable-tasks?version=0.0.0&flags=1 HTTP/1.1
Accept: application/json;api-version=3.0-preview.1
Host: jessehouwing:8080
User-Agent: node-Gallery-api
Authorization: Basic XXXXXXXXXXXXXXXX
X-TFS-FedAuthRedirect: Suppress
Connection: keep-alive
```

The `Host` header should contain `jessehouwing`, not `jessehouwing:8080`.

**Comment by trevorsg** [comment]
I will assign this to vsts-node-api.
