### ISSUE TITLE
Get Latest Source code from TFVC (not Git) using TFX-CLI

### ISSUE THREAD

**Issue by DreamingDevs** [Microsoft/tfs-cli#125]
Can we get latest source code from TFVC using TFX-CLI cmd? If not, can I know what are the other options.

Basically I have a team project in VSOnline under TFVC. I want to get source code from CMD and build it through my custom commands. I am not able to get the source code right now.

PS - I know the Git process, but I wanted to know about TFVC.

**Comment by trevorsg** [comment]
TFX-CLI is not designed for this scenario. Sounds like you want to use tf.exe, which is available from the Visual Studio Developer Command Prompt. [See here](https://msdn.microsoft.com/en-us/library/z51z7zy0(v=vs.100).aspx) for more information on using tf.exe.
