### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by iano123** [Microsoft/tfs-cli#127]
Hi ,

I am working for an organization that does not allow a connection to internet in the development machines (Yes they still exist).

How do I install this?

Thank You 
Jan

**Comment by trevorsg** [comment]
Within the next couple of weeks I will work on a standalone executable (which we're using internally, but if it's useful to others I can make it available as a download).

**Comment by iano123** [comment]
that would be super. meanwhile, can I install from source? How?

**Comment by trevorsg** [comment]
You will have to get nodejs installed on the machine, perhaps via USB stick. Then, on a separate computer, install NodeJS and NPM, and run `npm i -g tfx-cli`. Copy `%appdata%\npm` to the no-internet machine in the same location.

**Comment by dlez6c40** [comment]
Any update on this?

**Comment by trevorsg** [comment]
Sorry, no update, and nothing planned at this time. I don't have clearance from our legal team to distribute a standalone package. But you can create one yourself. After cloning the repo, run `npm install` and `npm run build`. Then you can copy node.exe, node_modules, and the build directories into an archive (e.g. a 7-zip self extracting archive). On the target machine, extract the archive and execute node.exe passing app.js as the first argument. Every argument after that will be an argument to TFX.

**Comment by iano123** [comment]
Thank you Trevor for the explination
