### ISSUE TITLE
Create vsix include .dll

### ISSUE THREAD

**Issue by twlikol** [Microsoft/tfs-cli#128]
I try to include some .dll file to vxis, but it is fail.

1>EXEC : error : spawn REG ENOENT
1>      at exports._errnoException (util.js:870:11)
1>      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
1>      at onErrorNT (internal/child_process.js:344:16)
1>      at nextTickCallbackWith2Args (node.js:442:9)
1>      at process._tickCallback (node.js:356:17)

I added the following line to VsixManifestBuilder.CONTENT_TYPE_MAP
".dll": "application/octet-stream"

It is working fine.

**Comment by trevorsg** [comment]
Fix available in next release.
