### ISSUE TITLE
Overriding extension id does not change contributions

### ISSUE THREAD

**Issue by jmezach** [Microsoft/tfs-cli#129]
When I explicitly pass the --extension-id parameter with a different value than what's in my manifest it correctly modifies it to match. However I'm developing a dashboard widget that includes configuration which requires me to have the following in my contributions:

```json
"contributions": [
    {
      "id": "ServerStatusWidget",
      "type": "ms.vss-dashboards-web.widget",
      "targets": [
        "ms.vss-dashboards-web.widget-catalog",
        "jonathan-mezach.new-relic-dashboard-widgets-private.ServerStatusWidget.Configuration"
      ],
```

Unfortunately the extension id in the targets section isn't modified so I end up with an invalid VSIX. It would be nice if this would work so I can keep a private ID in my source control and easily modify it during a build.

**Comment by trevorsg** [comment]
You should be able to leave out the publisher and extension id by using a relative ID. See https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/contributions-overview#identifying-contributions-and-types

**Comment by jmezach** [comment]
Ah, I see, didn't know that. Perhaps the documentation on [creating dashboard widgets](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/add-dashboard-widget#part-3-hello-world-with-configuration) could be improved to highlight this.
