### ISSUE TITLE
unsuccessful tfx-cli install - how to clean? (NodeJS version check needed)

### ISSUE THREAD

**Issue by DutchAt** [microsoft/tfs-cli#138]
I have an issue on one of my machines (Windows 10 one), see messages below. Tried to uninstall/install node.js, machine reboot, still ending up with the same output and tfx that doesn't work. Any pointers/ideas on how to clean this machine/install without reinstalling Windows or switching user profile? Everything is fine on another Win10 machine with approx. the same setup. Thanks in advance!

C:>npm install -g tfx-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
C:\Users\nlarin\AppData\Roaming\npm\tfx -> C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli_build\app\tfx-cli.js
tfx-cli@0.3.23 C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli
├── os-homedir@1.0.1
├── winreg@0.0.12
├── app-root-path@1.0.0
├── onecolor@2.5.0
├── colors@1.1.2
├── minimist@1.2.0
├── node-uuid@1.4.7
├── q@1.4.1
├── read@1.0.7 (mute-stream@0.0.6)
├── validator@3.43.0
├── async@1.5.2
├── tmp@0.0.26 (os-tmpdir@1.0.1)
├── shelljs@0.5.3
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.5, minimatch@2.0.10)
├── copy-paste@1.3.0 (sync-exec@0.6.2, iconv-lite@0.4.13)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.4.0, utile@0.2.1, winston@0.8.3)
├── jszip@2.5.0 (pako@0.2.9)
├── request@2.58.0 (caseless@0.10.0, oauth-sign@0.8.2, aws-sign2@0.5.0, forever-agent@0.6.1, tunnel-agent@0.4.3, stringstream@0.0.5, isstream@0.1.2, extend@2.0.1, json-stringify-safe@5.0.1, combined-stream@1.0.5, qs@3.1.0, tough-cookie@2.3.1, mime-types@2.0.14, bl@0.9.5, http-signature@0.11.0, form-data@1.0.0-rc4, hawk@2.3.1, har-validator@1.8.0)
├── tracer@0.7.4 (tinytim@0.1.1, colors@1.0.3, dateformat@1.0.11)
├── vso-node-api@3.1.1 (underscore@1.8.3)
├── archiver@0.14.4 (buffer-crc32@0.2.5, lazystream@0.1.0, async@0.9.2, readable-stream@1.0.34, tar-stream@1.1.5, zip-stream@0.5.2, glob@4.3.5, lodash@3.2.0)
├── lodash@3.9.3
├── inquirer@0.8.5 (ansi-regex@1.1.1, through@2.3.8, figures@1.7.0, cli-width@1.1.1, readline2@0.1.1, chalk@1.1.3, rx@2.5.3)
└── xml2js@0.4.17 (sax@1.2.1, xmlbuilder@4.2.1)

C:>tfx
TypeError: Object #<Object> has no method 'parse'

C:>

**Comment by trevorsg** [comment]
Hmm, I've never seen this before. Can you enable tracing and re-run tfx? To enable tracing, at a command prompt, type `set TFX_TRACE=1`.

**Comment by grawcho** [comment]
tfx-cli unsupported in Node 0.10 (>=0.12)
your log shows that you have node 0.10.33
install node from here [https://nodejs.org/en/download/](https://nodejs.org/en/download/)

**Comment by DutchAt** [comment]
@trevorsg: Here's the trace
C:\>set tfx_trace
TFX_TRACE=1

C:\>tfx
2016-07-27T01:35:58.474Z : TypeError: Object #<Object> has no method 'parse'
2016-07-27T01:35:58.474Z :     at C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\command.js:43:35
2016-07-27T01:35:58.474Z :     at Array.forEach (native)
2016-07-27T01:35:58.474Z :     at C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\command.js:38:15
2016-07-27T01:35:58.474Z :     at _fulfilled (C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:834:54)
2016-07-27T01:35:58.474Z :     at self.promiseDispatch.done (C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:863:30)
2016-07-27T01:35:58.474Z :     at Promise.promise.promiseDispatch (C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:796:13)
2016-07-27T01:35:58.474Z :     at C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:604:44
2016-07-27T01:35:58.474Z :     at runSingle (C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:137:13)
2016-07-27T01:35:58.474Z :     at flush (C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:125:13)
2016-07-27T01:35:58.474Z :     at process._tickCallback (node.js:419:13)
TypeError: Object #<Object> has no method 'parse'

**Comment by trevorsg** [comment]
@DutchAt Thanks. Did you see @grawcho's comment? Can you check your version of NodeJS? I thought we had a version check, but I guess not. I'll keep this issue open to add one.

**Comment by DutchAt** [comment]
@grawcho (and @trevorsg): I found out that I have old installation of 32-bit node on my machine (in addition to the current 64-bit that I've been trying to reinstall) and location of this installation is still in the PATH variable. Removed the old node from path/machine; reinstalled current 64-bit. Now I'm getting this: 

C:\Users\nlarin>npm i -g tfx-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\nlarin\AppData\Roaming\npm\tfx -> C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\tfx-cli.js
tfx-cli@0.3.23 C:\Users\nlarin\AppData\Roaming\npm\node_modules\tfx-cli
├── os-homedir@1.0.1
├── winreg@0.0.12
├── q@1.4.1
├── onecolor@2.5.0
├── async@1.5.2
├── app-root-path@1.0.0
├── validator@3.43.0
├── node-uuid@1.4.7
├── colors@1.1.2
├── minimist@1.2.0
├── read@1.0.7 (mute-stream@0.0.6)
├── tmp@0.0.26 (os-tmpdir@1.0.1)
├── shelljs@0.5.3
├── mkdirp@0.5.1 (minimist@0.0.8)
├── copy-paste@1.3.0 (sync-exec@0.6.2, iconv-lite@0.4.13)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.5, minimatch@2.0.10)
├── vso-node-api@3.1.1 (underscore@1.8.3)
├── jszip@2.5.0 (pako@0.2.9)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.4.0, winston@0.8.3, utile@0.2.1)
├── request@2.58.0 (aws-sign2@0.5.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, caseless@0.10.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@2.0.1, tough-cookie@2.3.1, qs@3.1.0, combined-stream@1.0.5, mime-types@2.0.14, http-signature@0.11.0, form-data@1.0.0-rc4, bl@0.9.5, hawk@2.3.1, har-validator@1.8.0)
├── tracer@0.7.4 (tinytim@0.1.1, colors@1.0.3, dateformat@1.0.11)
├── archiver@0.14.4 (buffer-crc32@0.2.5, async@0.9.2, lazystream@0.1.0, readable-stream@1.0.34, zip-stream@0.5.2, glob@4.3.5, tar-stream@1.1.5, lodash@3.2.0)
├── lodash@3.9.3
├── inquirer@0.8.5 (ansi-regex@1.1.1, through@2.3.8, cli-width@1.1.1, figures@1.7.0, readline2@0.1.1, chalk@1.1.3, rx@2.5.3)
└── xml2js@0.4.17 (sax@1.2.1, xmlbuilder@4.2.1)

But tfx then seems to work.

I agree adding node version check would be great. Suggest to mention multiple node installations referred in PATH variable in the error message. 

Thank you for prompt replies and your help!
Nik

**Comment by trevorsg** [comment]
Great, glad you got it working.

**Comment by AnnaOpareva** [comment]
@DutchAt  The answer to the question was provided, so we close this ticket. If you have any other questions, feel free to create new issues.
