### ISSUE TITLE
What holes does Basic Auth open up for an On-Premises TFS install?

### ISSUE THREAD

**Issue by joshjohanning** [microsoft/tfs-cli#142]
Referring to this tutorial: https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md

Thanks in advance.

**Comment by trevorsg** [comment]
Basic authentication is an authentication scheme that base64-encodes your credentials and sends them to the server as part of an HTTP header. Anyone who is able to intercept this request will gain access to your credentials (decoding base64 is trivial). Using HTTPS/SSL will significantly reduce the elevated risk associated with enabling basic auth.

**Comment by AnnaOpareva** [comment]
The answer to the question was provided, so we close this ticket. If you have any other questions, feel free to create new issues.
