### ISSUE TITLE
npm run build fails on fresh git clone

### ISSUE THREAD

**Issue by grawcho** [Microsoft/tfs-cli#153]
missing typings.
missing declarations in app modules.
please look at commits:
commit 830d077ddf71a2ace64e539e3208a89b1ad19d3f
commit 8cbc7b22e9e1860e2d011c503529469ba98c3853
commit d079e9ed76cae8d3d1092c0a1002ce62684eabdc
commit 704c65675e01b488151ae48ab3c6db6f81dbe766
commit 5ef5ce635620580ee6abec32949c5197ead57bcf
commit 283765906857b72dbdd3ec155c74cc4d73a4104f
for fixes.
i would expect that clone a latest from the repo would not require significant additional work to compile the application.
my fork compiles properly:

> tfx-cli@0.3.34 build /home/sfeldman/repos/tfs-cli
> tsc -p .
> tfx-cli@0.3.34 postbuild /home/sfeldman/repos/tfs-cli
> ncp app/tfx-cli.js _build/tfx-cli.js && ncp package.json _build/package.json

**Comment by isberg** [comment]
`npm run build` failed for me also but `npm install` did the trick, first installing dependencies and then building. The version was v0.3.37.

**Comment by grawcho** [comment]
agreed ... though there is no documentation regarding this (BTW i did it manually with tsd and typings install - and commited the typings in the typings folder)

**Comment by grawcho** [comment]
resolved ... a while ago.
