### ISSUE TITLE
tfs-cli - tfx build tasks create - does not create seed files

### ISSUE THREAD

**Issue by GregB-Roberts** [microsoft/tfs-cli#154]
This is on version 0.3.30
Seed files not create, I manually created the reference _resources dir but this made no difference.
Machine windows 8.1 x64

Thanks

tfx build tasks create

TFS Cross Platform Command Line Interface v0.3.30
Copyright Microsoft Corporation

> Task Name: SBSExampleTask
> Friendly Task Name: SBS Powerhell task
> Task Description: SBS powershell task
> Task Author: Greg Roberts
> cp: no such file or directory: C:\Users\gregr\AppData\Roaming\npm\node_modul
> es\tfx-cli_build\exec\build\tasks_resources\icon.png
> cp: no such file or directory: C:\Users\gregr\AppData\Roaming\npm\node_modul
> es\tfx-cli_build\exec\build\tasks_resources\sample.js
> cp: no such file or directory: C:\Users\gregr\AppData\Roaming\npm\node_modul
> es\tfx-cli_build\exec\build\tasks_resources\sample.ps1

created task @ C:\Users\gregr\SBSExampleTask
id   : 36190ea0-8f7b-11e6-9651-033f6ac3bbd5
name: SBSExampleTask

A temporary task icon was created.  Replace with a 32x32 png with transparencies

**Comment by AnnaOpareva** [comment]
Closed as a duplicate issue #151
