### ISSUE TITLE
WorkItemLinks query - Cannot read property 'map' of undefined.

### ISSUE THREAD

**Issue by aminner** [Microsoft/tfs-cli#160]
I was running into an issue with running a workitemlinks query to an on prem TFS  Version 14.0.24712.0. After looking around it looked like this shouldn't have been an issue (as far as the query went) and handled correctly. I went through and found the following object is returned for the workitemlinks query I was attempting to run:

![image](https://cloud.githubusercontent.com/assets/7517997/19651893/b5b71d1c-99dc-11e6-95bc-0a413efd670e.png)

The cause of the cannot map undefined is due to the following line of code that does the mapping for the returned query in the query.ts:

`let workItemIds = result.workItems.map(val => val.id).slice(0, Math.min(200, result.workItems.length));
`
I was able to fix the code so the query I was attempting to execute would map correctly, but am unsure if there may be a way around this or whether this is just a bug.

**Comment by mmanela** [comment]
I fixed the error in 2d73e865f4ae5cdd54a56c0d66a3540393bb613e.

However, more work will be needed to make the link output really good. For now I just resolve source and then target items in order.
