### ISSUE TITLE
tfx 0.3.38 stopped working on OSX

### ISSUE THREAD

**Issue by jmezach** [Microsoft/tfs-cli#162]
I just updated tfx-cli to 0.3.38 on my machine, but now I'm getting the following error:

```
bash-3.2$ tfx                                                                                                                
env: node\r: No such file or directory   
```

Looks like a line ending issue in tfx-cli.js. I'm running node 6.9.1 and npm 3.10.8 on macOS Sierra 10.12.1.

**Comment by ciriarte** [comment]
While we wait for this fix, an easy fix is to simply use dos2unix

```sh
dos2unix -F $(which tfx)
```

**Comment by mpseidel** [comment]
+1 - also breaks our builds on Ubuntu

Any ETA for a fix?

**Comment by halkeye** [comment]
Oh wow, thats what was going on? i never got around to looking into it

**Comment by Damovisa** [comment]
@trevorsg Can I confirm which version this was fixed in? I'm still seeing the issue in 0.3.43 on OSX.

**Comment by trevorsg** [comment]
@Damovisa Sorry about that - I actually regressed this issue recently. I got a new dev machine and forgot to disable autocrlf, so when I published, the CRLF returned. I have added a .gitattributes file to ensure this doesn't happen again. I re-published TFX with the correct line endings - please update to 0.3.44. Thanks.

**Comment by Damovisa** [comment]
@trevorsg Ah, perfect. Working now. Thanks!
