### ISSUE TITLE
"tfx extension" incorrectly prompts for a PAT (and then won't accept one if provided)

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/tfs-cli#168]
Issuing the command "tfx extension" prompts for a PAT, but then does not accept the provided PAT.

1. Not sure why TFX is prompting for a PAT
2. If it needs to prompt, it's failing to properly validate it (by continually asking to re-input one)

c:\xx>tfx extension
TFS Cross Platform Command Line Interface v0.3.39
Copyright Microsoft Corporation
> Personal access token:
error:   Invalid input for Personal access token:
> Personal access token:
error:   Invalid input for Personal access token:
> Personal access token:
error:   Invalid input for Personal access token:

**Comment by trevorsg** [comment]
The bug here is that the command should immediately display the help screen without asking for a PAT.
