### ISSUE TITLE
Checkout Files?

### ISSUE THREAD

**Issue by bcartmell** [microsoft/tfs-cli#178]
Is there any way to checkout files for edit in tfx-cli?  I can't seem to find a command or extension for this functionality.

**Comment by danielearwicker** [comment]
See https://github.com/Microsoft/tfs-cli/issues/125

The readme of this project should say in bold letters at the top: **This tool does not allow you to work with source code in your TFS repository.**

**Comment by grawcho** [comment]
it would be nice though, in the future, to incorporate the tf cli functionality in to tfx so only one command line tool will be needed. i'm sure this requires a lot of work and changes to vsts-node-api. this is a "nice to have" feature. defiantly not a priority.

**Comment by anatolybolshakov** [comment]
Hi everyone, there is a https://github.com/microsoft/azure-devops-node-api which could be used for this, tfx-cli is not intended to make checkout.

**Comment by anatolybolshakov** [comment]
Let me close this ticket at the moment - please feel free to ask any further questions.
