### ISSUE TITLE
Support for TFS  On-prem "extension install" command

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/tfs-cli#183]
There is an outstanding pullrequest made by @bfcamara from when he worked Microsoft, but it was never integrated and is now outdated. I tried to fix it up, but there have been too many changes for me to quickly see what's needed to make this work:

https://github.com/Microsoft/tfs-cli/pull/132

I've got a number of people asking for this feature:

https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/10

**Comment by pascalberger** [comment]
@trevorsg Any chance to get this PR updated and merged?

**Comment by trevorsg** [comment]
So, I'm out of the office for 2 full weeks starting tomorrow. If I have a chance at the end of the day I will see if I can get something working today. Otherwise it will be mid-May before I can take a look.

**Comment by trevorsg** [comment]
Sorry, I won't be able to get to this today.

**Comment by japj** [comment]
any update on this?

**Comment by FlexiGit** [comment]
Still no update?

**Comment by trevorsg** [comment]
I will be taking a look this week. I don't know if there are any blockers, but hopefully I can get something out by Friday or give a better update on this.

**Comment by trevorsg** [comment]
All done. Sorry it took... so long :(

`tfx extension install --service-url http://tfsserver:8080/tfs/DefaultCollection --token <PAT> --vsix myextension.vsix`
