### ISSUE TITLE
tfs-cli 0.3.49 client seems to be broken

### ISSUE THREAD

**Issue by yaananth** [microsoft/tfs-cli#193]
try `tfx login` before we used to get "login successful!" etc., responses, now we don't get any.

`tfx build tasks upload` is broken. Looks like it's sending `content-length` header (where as 0.3.25 did not send it), **with out** `content-range` header.

For others who has same problems, to go back to another version (I picked 0.3.25 not sure if version greater than that also works)

clone repo
From root of the repo:

- `git reset --hard 23a6bd1826ce402984e7c6150526b78d5472362e`
- `npm install`
- `npm install -g gulp`
- `gulp`

Move to `_build/app`
use `node tfx-cli.js` instead of `tfx` to run commands
eg:  `node tfx-cli.js login`

**Comment by anatolybolshakov** [comment]
@yaananth this seems to be the old version at the moment - do you have any issues with recent?

**Comment by yaananth** [comment]
Didn't try, closing as outdated
