### ISSUE TITLE
get a list of build definitions exist?

### ISSUE THREAD

**Issue by gencebay** [Microsoft/tfs-cli#194]
can tfs-cli get all build definitions that showed [Get a list of build definitions](https://www.visualstudio.com/en-us/docs/integrate/api/build/definitions) API so I'm trying to trigger all build definitions in specified project from tfs-cli?

**Comment by grawcho** [comment]
you can find this in one of these forks:
[grawcho](https://github.com/grawcho/tfs-cli)
[nchabra's](https://github.com/nchabra/tfs-cli/)

**Comment by grawcho** [comment]
just to be clear, you can use **_tfx build definitions list_** to get all definitions pipe the output via grep or sed to get a list of all build definitions and then iterate over this list with **_tfx build queue_**

**Comment by gencebay** [comment]
Thanks, I will do 👍
