### ISSUE TITLE
How to log into local team foundation server. 

### ISSUE THREAD

**Issue by staticcat** [Microsoft/tfs-cli#20]
The examples on the main page show how to log into visual studio online. What is the process for logging into an uploading a task for use on an team foundation server local installation?

I am currently stuck at logging into the tfs local machine with the command tfx login. Even using basic auth fails to log me in.

**Comment by teddyward** [comment]
Are you using version 0.1.9 of the npm module? We added support for on prem yesterday.

**Comment by teddyward** [comment]
I assume you've gone through the process of enabling basic creds for your local installation. There's a little guide here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/96aa6738-6f01-4015-8c59-25215cc84897/enable-alternative-credentials-in-tfs-on-on-premises?forum=tee

**Comment by bryanmacfarlane** [comment]
As Teddy noted, support was added yesterday for in prem for basic auth.  ntlm coming in a month or so

**Comment by staticcat** [comment]
Just to be clear for others that might come across this:

- Basic Auth needs to be added to the TFS Website under IIS
- Basic Auth needs to be added to the TFS virtual directory under IIS
- Other Auth types are allowed to remain and don't need to be removed (under IIS for both website and virtual directory)
- The prompt "Enter collection url" requires the full url to the collection in question, even if it is the default collection. 
- The prompt "Enter username" requires the domain and user name to be entered in the format "user@domain"

**Comment by staticcat** [comment]
@teddyward and @bryanmacfarlane thanks for the help on this.

**Comment by jessehouwing** [comment]
http://blog.jessehouwing.nl/2016/01/publish-build-tasks-to-tfs-2015-without.html
