### ISSUE TITLE
[VSTS-Ext-Tools] Install from 2015 and 2017 local marketplace

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/tfs-cli#204]
We've had multiple requests to support `tfx extension install` against a TFS 2015 or 2017 project collection URI. @bfcamara once built a pull request to support this #132, but the code is no longer mergable. The request has been voiced multiple times in the VSTS Developer Tools Build and Release Tasks marketplace reviews.

**Comment by trevorsg** [comment]
This is fixed now (sorry it took so long). 

`tfx extension install --service-url http://tfsserver:8080/tfs/DefaultCollection --token <PAT> --vsix myextension.vsix`

**Comment by jessehouwing** [comment]
Thanks @trevor!
