### ISSUE TITLE
[enhancement request] packagePath 1 source folder/file into 2 destinations

### ISSUE THREAD

**Issue by magnetmagnate** [Microsoft/tfs-cli#206]
VSTS extensions can contain multiple custom tasks, 2 or more of which may want to use the same file when packaged (e.g. identical icons).

currently neither of the following work for this:
```
"files": [
  {
    "path": "source/path",
    "packagePath": ["task1/path/dest", "task2/path/dest"]
  }
]
```
```
"files": [
  {
    "path": "source/path",
    "packagePath": "task1/path/dest"
  },
  {
    "path": "source/path",
    "packagePath": "task2/path/dest"
  }
]
```
It would be convenient for one or both of these examples to result in the same file being packaged in both specified destination paths.

**Comment by trevorsg** [comment]
I'm going to leave this feature undocumented. You can use an array of part names in the packagePath property - just like the first suggestion. There is currently no validation that the file hasn't already been added, Additionally, you are limited to a single content type for all files (hopefully that will be the same!) Let me know if it works for you.

**Comment by magnetmagnate** [comment]
on tfx-cli v0.4.4, this doesn't seem to be working for my current use case (packaging the VstsTaskSdk folder into 2 different Powershell-based custom tasks under 1 extension). I'm still only seeing the folder being packaged into the first destination path listed in the array.

**Comment by trevorsg** [comment]
@magnetmagnate I think I figured it out - go ahead and try 0.4.5 and let me know if that works. Thanks.

**Comment by magnetmagnate** [comment]
0.4.5 works. Thanks!

**Comment by trevorsg** [comment]
Good news!
