### ISSUE TITLE
Error on tfx login after update to 0.1.9

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/tfs-cli#22]
After login to the latest version I now get the following error on `tfx login`:

```
Message: Failed Request: Not Found(404) - https://mytenant.visualstudio.com/DefaultCollection/My%20Collection/_apis/connectionData
```

It worked with the previous version with the same collection url / access token

**Comment by bryanmacfarlane** [comment]
hmmm, I tried yesterday.  What url are you supplying in tfx login prompts?

It seems your url has Default Collection and My Collection

**Comment by pascalberger** [comment]
Yes, that was it. Thanks.

If I pass `https://mytenant.visualstudio.com/DefaultCollection` it works, if I pass `https://mytenant.visualstudio.com/DefaultCollection/My%20Collection` the error is thrown. This worked in the previous version, but since it asks for collection url and not project url, this makes sense

**Comment by bryanmacfarlane** [comment]
OK - just to be clear, is My Collection the name of your project?

Perhaps we can error with a better message if you don't:
1) supply a path segment of 1 segment or
2) it has two segments and the first one is 'tfs' (on-prem case)

What do you think?

**Comment by pascalberger** [comment]
Yeah, My Collection is the name of the project. 

Improved error message are never a bad idea :) For VSO case you might also check for the `https://` and the `visualstudio.com` part.

**Comment by bryanmacfarlane** [comment]
Yeah, we'll add more robustness and checking here.

We'll refrain from checking for visualstudio.com since we have test int envs etc... fragile.

Thanks!

**Comment by teddyward** [comment]
better error messages: f4c1d9906f68ea7b6a4317e4ca1702e04197fe0b
