### ISSUE TITLE
Error when quoting taskPath parameter with trailing backslash

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/tfs-cli#23]
The following call throws an `Specified directory does not exist` error:
```
tfx build tasks upload --taskPath "c:\mytask\"
```
With the quotes removed it works:
```
tfx build tasks upload --taskPath c:\mytask\
```
For path options it should be possible to quote the path (`tfx build tasks upload --taskPath c:\my task` also throws an `Specified directory does not exist` error)

**Comment by bryanmacfarlane** [comment]
doesn't the trailing slash escape the last quote?

"c:\mytask"

"c:\mytask\\"

??

**Comment by bryanmacfarlane** [comment]
That last one should be a double slash if your intent is to have a trailing slash

**Comment by pascalberger** [comment]
Yes seems so (`"c:\mytask"` works fine). But I wouldn't escaping expect to happen for command line tools. Especially since trailing backslashes are quite common in this case.

**Comment by teddyward** [comment]
not sure if I want to get rid of escaping entirely but commit 39d88b9d9dbac8c7f84f354e3d2fa9e722ac5506 strips leading and trailing quotes from file paths input by the user... which will at least solve this particular problem
