### ISSUE TITLE
Enable --rev-version to increase more than just strict SemVer-versions

### ISSUE THREAD

**Issue by janjaali** [Microsoft/tfs-cli#232]
Currently the --rev-version does not increase version numbers if the version number does not follow the SemVer pattern. It would be helpful if the --rev-version command would also increase not only SemVer version numbers and would behave instead more dynamically. (Especially in the context of VSTS-extension-development it is common to use build-numbers additional to the semver-version to deploy/test the extension in the marketplace).

## Proposed changes
--rev-version of a  semVer: 2.0.7 -> 2.0.8
--rev-version of a semVer+buildNumber: 2.0.7.411 -> 2.0.7.412

**Comment by trevorsg** [comment]
Fixed in defca45 - update will be published to npm soon.
