### ISSUE TITLE
Can't paste text at a TFX-CLI console

### ISSUE THREAD

**Issue by InteXX** [Microsoft/tfs-cli#237]
@trevorsg 

I'm unable to paste text at CLI prompts when running [`tfx-cli`][1].

I've just installed Node v8.9.1 LTS. Unfortunately, the `tfx-cli` install hung the first time through. I pressed `Ctrl+C` to cancel it, ran it again, and the second time it completed. (In the text that flashed across my screen during the second run, I believe I saw something about 'failed' and 'rollback.')

I don't know whether the initial failure is contributing to my problem.

When I run `tfx login`, I get this prompt first:

`> Service URL:`

I can type at this prompt, but I can't paste. Once I type the URL and press `Enter` I get this:

`> Personal access token:`

I can neither paste nor type at this prompt (or at least the cursor doesn't advance when I type). The only keys that seem to work here are `Enter` and `Ctrl+C`. Pressing `Enter` without typing anything results in this:

`error:   Invalid input for Personal access token:`

Pressing `Enter` after typing a few random characters sends no output to the console and simply dumps me back at the `C:\>` prompt.

How to fix this? How can one determine whether it's a Node problem or a `tfx-cli` problem? I suspect the latter but I'm not sure.

  [1]: https://www.npmjs.com/package/tfx-cli

**Comment by trevorsg** [comment]
The prompt for personal access token does not echo back what you type, but the input should still work (pasted or typed). If you still can't get it to work, you can always pass `--token abc123` to the original command instead.

**Comment by InteXX** [comment]
@trevorsg — Thank you, Trevor, that's a good tip.
