### ISSUE TITLE
tfx extension publish fails with: "Failed to find api location for area: gallery id: a41192c8-9525-4b58-bc86-179fa549d80d"

### ISSUE THREAD

**Issue by jorupp** [Microsoft/tfs-cli#242]
According to --fiddler, it's making this request (access token has full rights):

```
OPTIONS https://myorg.visualstudio.com:443/_apis/gallery HTTP/1.1
Accept: application/json
User-Agent: node-Gallery-api
Authorization: Basic <encoded-access-token>
X-TFS-FedAuthRedirect: Suppress
Host: myorg.visualstudio.com:443
Connection: keep-alive
```

And getting this response:
```
{"value":[],"count":0}
```

I'm able to publish my extension manually from the publisher portal (https://marketplace.visualstudio.com/manage/publishers/mypublisher), but `tfx extension publish` isn't working for me.  Am I doing something wrong here?

**Comment by trevorsg** [comment]
@jorupp What is the full command you are executing? You can omit the token.

**Comment by jorupp** [comment]
As I mentioned above, I'm running `tfx extension publish` from the command line, and I provided the HTTPS request made to VSTS.  Could you clarify what other information you're looking for?

**Comment by trevorsg** [comment]
Is it just `tfx extension publish` with no arguments? I would not expect it to make a request to myorg.visualstudio.com - all requests should go to marketplace.visualstudio.com. Try adding `--service-url https://marketplace.visualstudio.com`

**Comment by jorupp** [comment]
And of course, I try it again, and it *is* making an OPTIONS request to https://marketplace.visualstudio.com:443/_apis/gallery, but getting a 401 with a brand new full-access access token I created about 10 minutes ago.

Here's the full command I'm running now: `C:\projects\internal\vsts-project-health\Web>tfx extension publish -r ./package-base --rev-version --output-path ./package --overrides-file ./package-base/vss-extension.local.json --fiddler`


Command output:
```
TFS Cross Platform Command Line Interface v0.4.16
Copyright Microsoft Corporation
> Personal access token:
Checking if this extension is already published
It isn't, create a new extension.
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```

Request:
```
OPTIONS https://marketplace.visualstudio.com:443/_apis/gallery HTTP/1.1
Accept: application/json
User-Agent: node-Gallery-api
Authorization: Basic <token>
X-TFS-FedAuthRedirect: Suppress
Host: marketplace.visualstudio.com:443
Connection: keep-alive
```

Response:
```
HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/10.0
X-TFS-ProcessId: 1b78e795-05f3-478a-b340-a5318f90cca6
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 8050cda2-e065-41c7-badf-b556b9ad05b5
X-TFS-Session: 8050cda2-e065-41c7-badf-b556b9ad05b5
X-VSS-E2EID: 8050cda2-e065-41c7-badf-b556b9ad05b5
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Basic realm="https://app.market.visualstudio.com/"
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
X-Content-Type-Options: nosniff
Date: Thu, 21 Dec 2017 15:31:21 GMT
Content-Length: 0
```

I checked the request, and the auth header decodes to `OAuth:<my token>`, so I think the token is getting through right.

**Comment by trevorsg** [comment]
When you created your new PAT, did you select the "All accessible accounts" option in the dropdown? It looks like this:
![image](https://user-images.githubusercontent.com/397836/34263536-d556f936-e63d-11e7-881f-4ae974d24644.png)

**Comment by jorupp** [comment]
Didn't in the original one, but created another one about 15 minutes ago with that setting.

I should mention, on the marketplace site, I have 5 different directory options (my primary one, 3 others, and 'microsoft account').  The publisher I'm using was created in my primary one.  Maybe it's not getting mapped to right one of those or something?

**Comment by jorupp** [comment]
Ug... and I just generated *another* all-accessible PAT, and now it worked...
