### ISSUE TITLE
Add verbose version of -- JSON.

### ISSUE THREAD

**Issue by masters3d** [Microsoft/tfs-cli#243]
Some tools use the --JSON output to display to the user and do some logic. 
The JSON output only not verbose but I'd like to have the option to specify verbosity on the json output. 

JSON
```
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.

```
Regular output should be exposed to JSON with a --debug flag
```
Checking if this extension is already published
It isn't, create a new extension.
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
```

related: https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/55#issuecomment-350107672

**Comment by trevorsg** [comment]
With a8568c7b5, I have added `--trace-level` which can have a value of `info`, `debug`, and `none`. Default is info, except when the output type is changed, in which case the level defaults to `none`. Keep in mind, JSON output, errors, and warnings will always be printed regardless of this setting.

Example: `tfx extension publish --token xyz --json --trace-level info`

Update will be published to npm soon.
