### ISSUE TITLE
since version tfx-cli@0.4.13 @npm getting error during publish of an extension

### ISSUE THREAD

**Issue by davesmits** [Microsoft/tfs-cli#245]
using the  https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks extension in VSTS to publish extensions to the marketplace.

I did publication today with 0.4.11 and that been working; since its updated to 0.4.13 its broken.

results in the error:
2017-12-15T16:35:21.9423684Z error: TypeError: Cannot read property 'indexOf' of undefined
2017-12-15T16:35:21.9625179Z ##[error]tfx failed with error: Error: d:\a\_tools\tfx.cmd failed with return code: 4294967295

**Comment by trevorsg** [comment]
I have rolled back the update. Thanks for reporting.

**Comment by trevorsg** [comment]
Found the issue and fixed in 0.4.16. Thanks again.

**Comment by davesmits** [comment]
thanks!
