### ISSUE TITLE
Extension Validation times out during publishing - could not override fast defaults

### ISSUE THREAD

**Issue by nickhara** [Microsoft/tfs-cli#248]
`2017-12-20T19:16:57.8041612Z error: Error: Validation timed out. There may be a problem validating your extension. Please try again later.`
`2017-12-20T19:16:57.8261928Z ##[error]tfx failed with error: Error: d:\a\_tools\tfx.cmd failed with return code: 4294967295`

We have an extension in development (not public), that uses a 'Publish Extension' task which calls tfx-cli.  It started hitting the above error on 12/20.  We could see this corresponded to a newer tfx-cli version, which added new fast validation timeout values in the [PackagePublisher](https://github.com/Microsoft/tfs-cli/blob/master/app/exec/extension/_lib/publish.ts).  It appears that we are consistently exceeding the fast timeout, and I could not see how to extend the validation timeout with command-line options.  Additionally, we have seen cases where we hit the above error, but the extension was actually published.

**Comment by trevorsg** [comment]
The timeout period has changed and the error message now explains how to get the current validation status.

**Comment by nickhara** [comment]
Thank you! I will give it another try later tonight.

**Comment by nickhara** [comment]
It appears we have gotten past the previous error, but are now failing with a new error.  I'll look into this tomorrow morning.
```
2018-03-21T01:36:02.6710223Z `-- tfx-cli@0.5.10 
...
2018-03-21T01:36:02.7661502Z 421a7d2a-d750-4465-b905-c5db469e4efe exists true
2018-03-21T01:36:03.9538270Z [41merror: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.[49m
2018-03-21T01:36:03.9769786Z ##[error]tfx failed with error: Error: D:\a\_tools\tfx.cmd failed with return code: 4294967295
```

**Comment by Doetheman** [comment]
Was this issue ever resolved?

**Comment by T-Hugs** [comment]
I'm not able to reproduce any issues with publishing/validation right now. Can you provide more details?
