### ISSUE TITLE
build task create skips friendly name and fails

### ISSUE THREAD

**Issue by Suchiman** [Microsoft/tfs-cli#25]
First i've tried the current version on npm and tried to create a build task:
```
>tfx build tasks create
Copyright Microsoft Corporation

Enter short task name > sample
sample
Enter friendly name >
unhandled:
TypeError: Cannot read property 'toString' of null
    at AppData\Roaming\npm\node_modules\tfx-cli\lib\inputs.js:70:65
    at Interface.onLine (AppData\Roaming\npm\node_modules\tfx-cli\node_modules\read\lib\read.js:111:5)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface._line (readline.js:546:8)
    at Interface._ttyWrite (readline.js:830:16)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
```
Here i just typed 'sample', hit enter, it got echoed back, it skipped the friendly name input and failed with the exception.

I've then build master @e438b2904d6a96aca84e35679a0260851a851259
```
>tfx build tasks create
Copyright Microsoft Corporation

Enter short task name > sample
sample
Enter friendly name >
Enter description > sample
Enter author > sample
Error: friendlyname is required.
```
Which then echoed the first sample back and skipped friendly name again, finally failing with `friendlyname is required`

With trace turned on:
```
>tfx build tasks create
2015-08-16T20:48:47.376Z : loader.load
2015-08-16T20:48:47.378Z : build-list.js
2015-08-16T20:48:47.378Z : build-queue.js
2015-08-16T20:48:47.379Z : build-show.js
2015-08-16T20:48:47.379Z : build-tasks-create.js
2015-08-16T20:48:47.379Z : build-tasks-delete.js
2015-08-16T20:48:47.379Z : build-tasks-list.js
2015-08-16T20:48:47.379Z : build-tasks-upload.js
2015-08-16T20:48:47.379Z : build-tasks.js
2015-08-16T20:48:47.379Z : build.js
2015-08-16T20:48:47.380Z : help.js
2015-08-16T20:48:47.380Z : login.js
2015-08-16T20:48:47.383Z : parse.js
2015-08-16T20:48:47.383Z : resources
2015-08-16T20:48:47.386Z : version.js
2015-08-16T20:48:47.386Z : loader.match
2015-08-16T20:48:47.393Z : Command matched
2015-08-16T20:48:47.393Z : No command matched
2015-08-16T20:48:47.404Z : loaded AppData\Roaming\npm\node_modules\tfx-cli\exec\build-tasks-create.js
Copyright Microsoft Corporation

2015-08-16T20:48:47.405Z : build-create.exec
2015-08-16T20:48:47.405Z : tfcommand.promptArguments
2015-08-16T20:48:47.406Z : inputs.prompt
Enter short task name > sample
sample
2015-08-16T20:48:52.709Z : read: sample
Enter friendly name >
2015-08-16T20:48:52.711Z : read: null
Enter description > sample
2015-08-16T20:48:59.027Z : read: sample
Enter author > sample
2015-08-16T20:49:00.139Z : read: sample
2015-08-16T20:49:00.140Z : friendlyname is required.
2015-08-16T20:49:00.141Z : Failed to gather inputs. Message: friendlyname is required.
Error: friendlyname is required.
```

**Comment by teddyward** [comment]
hi.  sorry you're having trouble.  Works for me on windows right now.  What setup are you running?  Did you install globally from npm right before running the command the first time?  Did you regulp the project and install from the _build/app folder after pulling from master?  Try following the steps exactly as shown in the pictures below.  

When pulling down from npm:
<img width="519" alt="from npm" src="https://cloud.githubusercontent.com/assets/5324890/9295580/64b1d1fc-4440-11e5-8e79-ed31568b3a3b.png">

When building from source:
<img width="530" alt="create tasks" src="https://cloud.githubusercontent.com/assets/5324890/9295583/76fe23ce-4440-11e5-9771-1dd1a619da42.png">

**Comment by teddyward** [comment]
let me know if that works.  hopefully it helps.  what's really weird is the fact that it's echoing the task name back to you... I think that's the cause of the problem you're having, but I don't see that logic anywhere the history of inputs.ts prompt/get method... so send me info about your workflow if that ^ doesn't work...
https://github.com/Microsoft/tfs-cli/blob/master/app/lib/inputs.ts

**Comment by Suchiman** [comment]
I've figured it out, apparently it's not a bug in tfx but rather in io.js.
This is my first time on npm / node.js so i went to https://www.npmjs.com/ to get npm which is required to install tfx.
On the bottom on the page under `installing npm` it provided two links, one for io.js and one for node. I've picked the first one to io.js.
Now i've uninstalled io.js, installed node.js from the second link and now it's working!

Sorry for the confusion, it might should be mentioned in the readme that io.js can cause problems, not sure if investigation is worth it, reading on the node page that io.js is being merged back into node.

**Comment by bryanmacfarlane** [comment]
Yes.  Our github main page has the link to install node (not io.js)

**Comment by Suchiman** [comment]
@bryanmacfarlane i'm sorry, i've checked https://github.com/Microsoft/tfs-cli/blob/master/README.md , all files inside docs, and the wiki but none of them mentions node, they all assume you already have npm installed (and the npm webpage offers io.js first)

**Comment by bryanmacfarlane** [comment]
oooh - you're correct.  I was mixing up with https://github.com/Microsoft/vso-agent which does.

Want to do a PR?  If not, I can

**Comment by Suchiman** [comment]
You can do that, i'm off the road right now

**Comment by carlsonad** [comment]
I'm still experiencing this problem.  The behavior is a little bit different.

Here's an example of the output:

![image](https://cloud.githubusercontent.com/assets/12514767/10355387/d751f08e-6d30-11e5-8d44-bc87314911dc.png)

The short task name is echoed and the friendly name is skipped.

I installed npm with the latest node release from this url:  https://nodejs.org/download/release/latest/

**Comment by Suchiman** [comment]
I haven't tested it yet but i've recently read that IO.JS merged back into NodeJS so this error might have propagated.

**Comment by carlsonad** [comment]
I installed an older version of [node](https://nodejs.org/en/blog/release/v0.10.36/) and now it works.

**Comment by HSAR** [comment]
So anything lower than 4.X will do? I'm having this problem on 4.1.2.

**Comment by carlsonad** [comment]
I don't think anything lower then 4.x will do.  I know [0.12.7](https://nodejs.org/dist/v0.12.7/x64/) works.  I think that was that last release before the merge with io.js.

**Comment by scottdallamura** [comment]
I have a trivial repro that works with 0.12.x and fails with 4.0.0 and 4.1.2.  readline echoes the first input line back, which does look related.  Interestingly, it doesn't echo subsequent lines.

**Comment by peterM** [comment]
I have the same issue ...when can we expect fix ?

**Comment by bryanmacfarlane** [comment]
Use node 0.12.7.  It's a bug in node4.0.0 that hasn't been fixed yet.  I don't have the link handy but I'll include it.

**Comment by CharlesSterling** [comment]
Just wanted to verify this bug is still present

**Comment by trevorsg** [comment]
We're releasing a large update to tfx-cli today, and this issue should be fixed. I revamped the arg prompting logic, and it now implements a queue of prompts so that the next prompt won't be shown until we have a value for the previous.
