### ISSUE TITLE
extension invalid command

### ISSUE THREAD

**Issue by addatwork** [Microsoft/tfs-cli#252]
Hello,

I'm trying to pack an extension using

`tfx extension create --manifest-globs c:\dump\home\vss-extension.json`

And i get an error

`tfx: "extension" is invalid, please see other available commands`

Am i doing anything wrong? The same result if I call any command so i'm pretty sure it's a setup thing.

`tfx -v
1.1.0`

**Comment by trevorsg** [comment]
Looks like you installed `tfx`, not `tfx-cli`. Sorry, it's confusing. You want to run `npm install --global tfx-cli` and then you can run it with `tfx extension create --manifests C:\dump\home\vss-extension.json`.
