### ISSUE TITLE
Broken extension install --vsix 

### ISSUE THREAD

**Issue by giuliov** [Microsoft/tfs-cli#253]
I run
`tfx extension install --vsix .\my.sample-extension-0.0.1.vsix --service-url https://MY-LOCAL-TFS/ --token PAT-FOR-MY-LOCAL-TFS`

and got this error
```
TFS Cross Platform Command Line Interface v0.5.4
Copyright Microsoft Corporation
error: Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
```
looks like a change in a dependent library

**Comment by calebcartwright** [comment]
I am getting the exact same error too and it is breaking my release pipeline (using TFS CLI v0.5.4). Sharing some info I've found in case any of it is useful:

- [This commit](https://github.com/Microsoft/tfs-cli/commit/c53037463b8693d05ee8e37b7701b8f772d9af2c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) changed the TFS CLI dependency on `jszip` from 2.x to 3.x
- In v3.x of `jszip` lib, there were a number of changes to the API, including the removal of the constructor with a parameter
  -  See the `jszip` [2.x to 3.x upgrade guide](http://stuk.github.io/jszip/documentation/upgrade_guide.html)
  -  Any parameters passed to the `jszip` [3.x constructor result in an error being thrown](https://github.com/Stuk/jszip/blob/master/lib/index.js#L13) with the precise error message being emitted by the TFS CLI
- The TFS CLI codebase is using the deprecated `jszip` 3.x constructor in [extensioninfo.ts](https://github.com/Microsoft/tfs-cli/blob/b2c4ad39969ffe0b7ca44bff916b89ddf473c582/app/exec/extension/_lib/extensioninfo.ts#L34)

**Comment by trevorsg** [comment]
Fixed
