### ISSUE TITLE
[Meta] Git tag this repo's releases and use the GitHub Release tab

### ISSUE THREAD

**Issue by nschonni** [Microsoft/tfs-cli#254]
https://github.com/blog/1547-release-your-software
This makes it easier to see when new versions are release, and to see what has changed between releases, even if a changelog isn't provided.

**Comment by trevorsg** [comment]
Oh I guesssssssssssss :)

**Comment by nschonni** [comment]
Awesome ❤️ ❤️ ❤️ 
Would be great to go back and tag the old ones if possible too 😉

**Comment by nschonni** [comment]
@trevorsg it looks like this stopped after 0.5.10, could you please tag the last few releases :heart:
