### ISSUE TITLE
create extension with --rev-version increases version number in package.json but deploys old

### ISSUE THREAD

**Issue by GraueEminenz79** [Microsoft/tfs-cli#255]
Hello,
the following command
`tfx extension create --rev-version`
increases the extension version number in package.json but the bundled .vsix file carries the old version number.

TFS Cross Platform Command Line Interface v0.5.4

**Comment by nschonni** [comment]
`--rev-version` should be updating `vss-extension.json` not the package.json, or is there something else going on?

**Comment by trevorsg** [comment]
Assuming you mean vss-extension.json and not package.json, this should be fixed in the latest version.
