### ISSUE TITLE
I cannot run tfx after installation

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/tfs-cli#26]
What have I missed, I've followed the instructions from the document by installing on a Windows 10 machine via the command prompt:

npm install -g tfx-cli, the installation seems to work but any attempts to run tfx simply returns tfx is not recognised as an internal or external command, operable program or batch file.

I've also tried running the install from a command window as Administrator with the same result.

**Comment by bryanmacfarlane** [comment]
can you include the output of when you ran the global install?

**Comment by johnkattenhorn** [comment]
Sure thing, I'm no node / npm expert but looks like it works.

![image](https://cloud.githubusercontent.com/assets/616249/9340888/760e64dc-45ea-11e5-82bd-79dd8fae290a.png)

**Comment by teddyward** [comment]
is C:\Users\johnk\AppData\Roaming\npm in your path?  might have been an option when installing node.

**Comment by johnkattenhorn** [comment]
Bingo, thanks @teddyward seems that the installation of node from a full VS2015 install doesn't add the NPM directory to the path by default.

Doing a
    set PATH=%PATH%;C:\Users\johnk\AppData\Roaming\npm

Did the trick!

**Comment by teddyward** [comment]
great! thanks @bryanmacfarlane for the idea

**Comment by bryanmacfarlane** [comment]
Cool - would be good to add to our docs in a troubleshooting section (a sub markdown)

**Comment by johnkattenhorn** [comment]
Cool, wish the Personal Token entry would accept a paste or maybe allow the token to be echoed onto the screen too, took a while to enter it properly :-)

**Comment by johnkattenhorn** [comment]
It's pretty cool though, custom task straight in.

**Comment by teddyward** [comment]
Yeah -- I'm planning on adding a bunch to the docs later this week.  Pasting PAT tokens should work... but I use powershell so it's a bit different... I'll play with it

**Comment by bryanmacfarlane** [comment]
I pasted in win cmd shell via top left menu, edit, paste.  you don't want to have to type that ...

**Comment by johnkattenhorn** [comment]
I tried that a got a blow up a about null string so I assumed it had failed. So I typed it in very slowly and carefully ;-)

![image](https://cloud.githubusercontent.com/assets/616249/9341503/49603f6a-45ee-11e5-890c-24a6892adaf2.png)

**Comment by bryanmacfarlane** [comment]
hmmm - id used that icon in the upperleft of toolbar, edit, paste and worked.
regardless, we should fix the null ref on the toString and report no password received

**Comment by teddyward** [comment]
fixed that a while back... it's in master and will go up with 0.1.10

**Comment by teddyward** [comment]
see: d9f167d5afd44a9984d206f4afae47a7e884526d
