### ISSUE TITLE
Unable to login with on premises

### ISSUE THREAD

**Issue by Quantumplation** [Microsoft/tfs-cli#27]
Hello,

I have enabled Basic authentication on TFS, created a local user account, and am able to log in with that from my browser.

When trying to log in with tfx login --authtype basic, I receive:

   Error: Connection failed. Check your internet connection & collection URL.
   Message: Failed Request: Internal Server Error(500) - [colleciton URL]/_apis/connectionData

If I visit [collection URL]/_apis/connectionData in my browser, I receive a JSON response which describes the user I created, in particular, NOT a 500 error.

**Comment by teddyward** [comment]
that's bizarre.  I just reinstalled from npm and logged in successfully so should be working for most cases.  Did you try to login immediately after installing today?

what happens if you try to log in using a newly generated PAT token?  (my profile > security > personal access tokens)

Might be some weird environment variable you have set... not sure.

**Comment by bryanmacfarlane** [comment]
See the troubleshooting section in the readme.  Set the trace envvar.   Also make sure to set:  TFX_TRACE_CREDS=1  or  TFX_TRACE_CACHE=1  (and please don't send - 4U to see if the creds are right).

Finally, if that doesn't offer clues, the node api allows setting HTTP_PROXY envvar with the url to fiddler or Charles proxy and it will send all requests there.  Remember to clear it.  Let me know if you need more guidance here.  I'll extend the troubleshooting section if needed.

Either way, shouldn't be a 500

**Comment by Quantumplation** [comment]
@teddyward Fresh installed today!  Does on premise TFS support Personal access tokens? I didn't see the functionality anywhere, and i've been looking for a while.

@bryanmacfarlane I set TFX_TRACE_CREDS and all of a sudden it worked.  Unset the variable, and it still works.  Must have been some kind of caching issue?

**Comment by teddyward** [comment]
oh. you're right. sorry, I totally spaced out. No PAT in tfx.

Glad it works now!  maybe it was a cache error but also could have been a transient error... thanks for letting us know, anyway.

**Comment by bryanmacfarlane** [comment]
Yeah, was either a caching issue or a transient server issue??
