### ISSUE TITLE
tfx extension install fails if already installed

### ISSUE THREAD

**Issue by pabrams** [microsoft/tfs-cli#272]
I'm trying to publish an extension to other extension environments, in tfs build/release.

`tfx extension install --vsix (vsix) --service-url (serviceUrl) --pat (pat)`

> error: Error: Failed Request: Conflict(409) - TF1590010: Extension (extension name) is already installed in this account.

Does this need to be an error?  Couldn't it be a warning instead?  If it's already installed, that's good. 

I guess I need to wrap or catch this somehow so my build doesn't fail.

**Comment by trevorsg** [comment]
We could probably do this. The API would stay the same and continue to return a 409, but I can look for that error in TFX and issue a warning instead of an error.

**Comment by BastienPerdriau** [comment]
Totally agreed with @corystein , a force switch or an uninstall option could be more convenient.
Using the Azure DevOps tasks, which use tfx, it would be cool when doing CI/CD.

**Comment by shudv** [comment]
@trevorsg any progress on this?

**Comment by trevorsg** [comment]
Sorry, I fixed this in 0.7.1 but forgot to close out the issue.
