### ISSUE TITLE
Requires NPM 8?

### ISSUE THREAD

**Issue by JasonGoemaat** [Microsoft/tfs-cli#288]
Maybe something's wrong with my system, but package.json says it requires NPM version 8 or greater:

```
    "engines": {
        "npm": ">=8.0.0"
    },
```

Is nobody else getting an error trying to install this since the most current version of npm is only 6.4.1?

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/tfs-cli/blame/master/package.json#L64
