### ISSUE TITLE
For tfx login command with on-premises specifying server url and not collection url succeeds but causes errors later

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/tfs-cli#29]
When using the login command you are prompted for a collection url but are able to specify the server url without an error condition being raised (i.e http://server:8080/tfs instead of http://server:8080/tfs/collection  )

You are able to successfully login but then when issuing commands such as tfx build list you get strange errors and it is not clear why. Once the actual collection URL is specified instead everything works as expected.

I would recommend alerting the user if they are not specifying a collection url.

**Comment by yansklyarenko** [comment]
@bbusacker Have you ever faced with the following error running login command?
> Error: Connection failed. Check your internet connection & collection URL.
> Message: connect ECONNREFUSED

I'm trying to **tfx login --authtype basic**. The connection URL looks correct - I do enter the collection URL, tried that with and without the trailing slash. 
The basic auth is installed as a web server role feature and enabled in IIS for TFS website. 

Any ideas what could that be?

**Comment by bryanmacfarlane** [comment]
it's hard to say without any details.  My first guess is you didn't enable basic auth correctly - it's should be enabled on the IIS application (/tfs) and not necessarily the root web site.  

Either way this isn't related to the suggestion/issue logged here.

**Comment by bbusacker** [comment]
I’ve not seen that.   The collection url should be http://servername:port/tfs/CollectionName just to double check.

**Comment by yansklyarenko** [comment]
Guys, I apologize - the problem has nothing to do with the tool, it works just fine. I was able to login with basic auth. I've just dumped the real problem and the solution to the [blog post](http://sklyarenko.net/blog/2015/08/27/err-connection-refused/).

**Comment by bryanmacfarlane** [comment]
Glad you figured it out.  Thanks
