### ISSUE TITLE
Unable to install extension using tfx:  The requested extension 'Publisher.ExtensionName' doesn't exist.

### ISSUE THREAD

**Issue by Liero** [Microsoft/tfs-cli#294]
I create extension like using:

    tfx extension create --manifest-globs "vss-extension.json"

and then run:
 
    tfx extension install --vsix "Liero.Libman-0.1.0.vsix"

but I always get:

> The requested extension 'Liero.Libman' doesn't exist.

my vss-extension.json:
{
    "manifestVersion": 1,
    "id": "Libman",
    "version": "0.1.0",
    "name": "Libman",
    "description": "Client side scripts package manager for ASP.NET Core",
    "publisher": "Liero",
    "public": false,
    "categories": ["Pipelines"],
    "targets": [
        {
            "id": "Microsoft.VisualStudio.Services"
        }
    ],
    "icons": {
        "default": "icon.png"
        
    },
    "content": {
        "details": {
            "path": "README.md"
        }
    },
    "contributions": [
        {
            "id": "libman",
            "type": "ms.vss-distributed-task.task",
            "targets": [
                "ms.vss-distributed-task.tasks"
            ],
            "properties": {
                "name": "libman"
            }
        }
    ],
    "files": [
        {
            "path": "libmantask"
        }
    ],
    "tags": [
        "libman",
        "package",
        "manager",
        "asp.net",
        "javascript",
        "library"
    ]
}

_TFX CLI Version: 0.6.3_

**Comment by jessehouwing** [comment]
You must first publish before you can install.
