### ISSUE TITLE
Validation of manifest incomplete

### ISSUE THREAD

**Issue by hferentschik** [Microsoft/tfs-cli#295]
I am developing an extension for Azure DevOps. As part of my development process, I want to publish two extensions. One public for actual use and one private for ongoing development. 

As part of my build process, I am building the extension twice, where on the second call to 'tfx extension create' I use the overrides-file flag to point to a JSON file with manifest override values, eg

```JSON
{
    "name": "OpenShift Extension (dev)",
    "public": "false"
}
```

Note in the example above I used quotes around false. It should have been just _false_. Using this override, my extension was created and published without warning and I ended up with a public extension. 

I would have expected better validation of this value, preventing me from using the additional quotes, especially for the _public_ attribute.

**Comment by hferentschik** [comment]
The same applies when using the 'override' flag.

**Comment by trevorsg** [comment]
While validating the entire schema is a bit out of scope for me, I will add a validation for public, since it's potentially dangerous.
