### ISSUE TITLE
Conflict / overwrite - IIS Web AppDeploy

### ISSUE THREAD

**Issue by blsher** [Microsoft/tfs-cli#30]
So, i was messing around with this, trying to get with one of the VSO agent tasks uploaded; the IISWebAppDeploy.

Not sure what's going on but,

Error: Failed Request: Conflict(409) - https://*.visualstudio.com/_apis/distributedtask/tasks/89A3A82D-4B3E-4A09-8D40-A793849DC94F?overwrite=false

I fired a command up for the IISWebAppDeploy script.  From the build output directory that i took from the vsoAgent git repo.

I do a build tasks list, and the code 89A3A82D-4B3E-4A09-8D40-A793849DC94F doesn't exist.  Can't find it anywhere, checked the UX and it doesn't seem to have it.

I checked the task.json, and it is the right one, i'm just wondering why it think it's already there.

{
    "id": "89A3A82D-4B3E-4A09-8D40-A793849DC94F",
    "name": "IISWebAppDeployment",
    "friendlyName": "IIS Web Application Deployment",
    "description": "Deploy Web Application using MSDeploy to IIS Web Site",
    "helpMarkDown": "[More Information](http://aka.ms/iiswebappdeployreadme)",
    "category": "Deploy"
}

And when i go to use ./Chef and upload it, it says Task at : ./Chef has succeeded upload, etc..
But going to the UX and the tasks list, doesn't show chef at all.

Cache maybe? On the ux end?

**Comment by bryanmacfarlane** [comment]
Because it is their in the backend but it's behind a feature flag not enabled for customers yet.

You shouldn't be using this tool to upload the inthebox tasks that we own in the tasks repo.  Those are our tasks and the code in them is often code against services that are one or two sprints (weeks) from being deployed).  You can't take future code from master code and just push it into production.

The tool is for uploading your custom tasks or potentially a patched task of ours that we hand out.

**Comment by blsher** [comment]
Ahh, well this is very cool.  Book marked for deep diving.

**Comment by bryanmacfarlane** [comment]
I will add a note to the readme.

If you want to test the mechanism, see the video where I create a hello world task.

We open source as examples of how to do it :)

In the next release, we want to make sure a task delcares which task lib it's coding against so if the server doesn't have that task lib, it will tell you.  That will make it so you can upload ones as long as the server/api supports it but will bark if you're getting ahead of it.  We realize it's a problem.

**Comment by blsher** [comment]
Must have been one of those afternoons, I'm told the guy that's creating the custom task as a test is about done, so I'll try to push that around (he watched the video suppose i should have to! :)),   But yeah that was my next question about getting ahead of it.  Thanks for that.

Side note: This set up gave me the green light from those above me :) to aggressively convert all RM (on prem xaml builds from 2013 to vNext) yay.  Can't wait for the rest of the agent/task templates to go up.

**Comment by davidsk** [comment]
@bryanmacfarlane I have exactly this issue.  How can we identify which tasks are 'inthebox'?

**Comment by bryanmacfarlane** [comment]
In the box tasks are in this repo: https://github.com/Microsoft/vso-agent-tasks

**Comment by bryanmacfarlane** [comment]
It's already there because it's deployed in the box but it's in preview so you can't see it.

**Comment by kmkumaran** [comment]
Reach out to RM_Customer_Queries@microsoft.com, if you would like to get enrolled for preview tasks.

**Comment by davidsk** [comment]
Is there a preview mechanism for on-prem?

Presumably once tasks are allowed out of the box they'll either be pre-installed or available in the marketplace, right?

**Comment by kmkumaran** [comment]
No preview mechanism for on-prem. We are evaluating the right mechanism (pre-installed vs marketplace) for these tasks to be available. We will share details once we have more info.
