### ISSUE TITLE
TFS Build Fails at Get Sources Step. Workspace Delete!

### ISSUE THREAD

**Issue by vinaysandela** [microsoft/tfs-cli#304]
My Build Failing and when I see Get Sources, The Workspace Source folder is being deleted(line 144). My Code is in TFVC. It it not pulling the code.

Can you please check the log- 
[1_Build.txt](https://github.com/Microsoft/tfs-cli/files/2658899/1_Build.txt)

I have checked for permissions and it looks good. Please let me know. I am using TFS OnPrem 2017.1 Thanks

**Comment by anatolybolshakov** [comment]
Hi @vinaysandela closing this one here since it's not related to tfx-cli.
