### ISSUE TITLE
running `tfx extension --help` using 0.6.4 tries to connect to internet

### ISSUE THREAD

**Issue by pabrams** [Microsoft/tfs-cli#308]
I just tried to upgrade to tfx-cli 0.6.4 and for some reason when I display help it's trying to connect to visualstudio.com.

tfx-cli 0.5.10 doesn't do this.  What's happening?

> C:\Users\Paul.Abrams>tfx extension --help
> TFS Cross Platform Command Line Interface v0.6.4
> Copyright Microsoft Corporation
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 1)
> (node:7196) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
> cated. In the future, promise rejections that are not handled will terminate the
>  Node.js process with a non-zero exit code.
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 2)
> (node:7196) PromiseRejectionHandledWarning: Promise rejection was handled asynch
> ronously (rejection id: 2)
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 4)
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 5)
> 
> Available commands and command groups in tfx / extension:
>  - isvalid: Show the validation status of a given extension.
>  - create: Create a vsix package for an extension.
>  - publish: Publish a Visual Studio Marketplace Extension.
>  - share: Share an Azure DevOps Extension with Azure DevOps Organizations.
>  - show: Show info about a published Azure DevOps Services Extension.
>  - init: Initialize a directory for development of a new Azure DevOps extension.
> 
>  - install: Install a Azure DevOps Extension to a list of Azure DevOps Organizat
> ions.
>  - unshare: Unshare a Azure Devops Extension with Azure DevOps Organizations.
>  - resources: Commands for working with localization of extensions.
>  - publisher: Commands for managing Visual Studio Marketplace Publishers.
> 
> 
> For help with an individual command, type tfx extension <command> --help
> 
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 6)
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 7)
> (node:7196) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN app.v
> ssps.visualstudio.com:443
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> (node:7196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
>  id: 8)
> 
> C:\Users\Paul.Abrams>

**Comment by trevorsg** [comment]
Sorry about that. We now make an http request to get the URL for the Marketplace. Since the `--help` option actually loads commands to figure out what their options are, it was making this request simply by loading these commands. Will have it fixed in the next update.
