### ISSUE TITLE
Introduce the silent mode

### ISSUE THREAD

**Issue by yansklyarenko** [Microsoft/tfs-cli#31]
As far as I can tell, the tool can only login interactively. If I specify a collection URL in the command line, it still prompts for it. Do you think it makes sense to introduce the silent mode?

Here is the scenario. I'm working on a custom build step, and each time I push I'd like my CI server to 'tfx build tasks upload' my step to the playground TFS instance. Does it make sense?

Please, let me know if I'm missing anything. Thanks!

**Comment by bryanmacfarlane** [comment]
Should be able to provide all inputs (including creds) on the CL.  Perhaps it regressed - will investigate ...

**Comment by trevorsg** [comment]
Fixed with latest release.
