### ISSUE TITLE
Add support to uninstall an extension from servers' local gallery

### ISSUE THREAD

**Issue by gereon77** [Microsoft/tfs-cli#316]
Right now I miss the possibility to uninstall an extension from the local extension gallery of the Azure DevOps Server instance. This would be very helpful during extension development. Right now I have a work around with a pure REST call (DELETE {server_url}/_apis/gallery/publishers/{publisher}/extensions/{extensionId}) which does the trick but I would love to see this supported by tfx cli so I don't need to handle authentication on my own.

Thank you in advance. :)

**Comment by trevorsg** [comment]
Should be pretty straightforward. Will add this in an update today.

**Comment by trevorsg** [comment]
Fixed in 0.7.5

**Comment by trevorsg** [comment]
By the way, the command is `tfx extension unpublish`.

**Comment by gereon77** [comment]
merci
