### ISSUE TITLE
Scaffolding pattern for a repo with several powershell-based custom tasks

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/tfs-cli#335]
Hi, I've created a repository with several powershell-based custom tasks and the current folder structure looks like:

```
|-- src
|     |-- task1
|     |      |-- ps_modules
|     |      |        |-- vststasksdk
|     |      |-- task.json
|     |      |-- task1.ps1
|     |      |-- icon.png
|     |      |-- package.json
|     |
|     |-- task2
|            |-- ps_modules
|            |        |-- vststasksdk
|            |-- task.json
|            |-- task2.ps1
|            |-- icon.png
|            |-- package.json
|-- tools
|      |-- publish-updatedcustomtasks.ps1
|-- .gitignore
|-- readme.md
.....
```
If I wanted to bundle all of the custom tasks as a VSIX extension, what else would I need to add and how do i version it?

Currently, I'm manually versioning each task's task.json file before I commit and push to repo.
The CI pipeline invokes the powershell script publish-updatedcustomtasks.ps1 to find all the updated task.json files. If there are any, it invokes `tfx login`, iterates through all the updated tasks calling `tfx build tasks upload --task-path <task.json parent folder>` and at completion, invokes `tfx logout`. How should I modify my CI pipeline and folder structure if I want to publish all of the custom tasks as a VSIX manifest? I would still need to manually bump the version of each task, in addition to the vsix version, right? I also noticed that I get execution errors for my custom tasks at the end if I don't provide a package.json file.

**Comment by anatolybolshakov** [comment]
Hi @tristanbarcelon yes, you will still need to bump every task version - for them to be updated properly on agent.

**Comment by anatolybolshakov** [comment]
@tristanbarcelon let me close this one at the moment - please feel free to ping if you have any further questions.
