### ISSUE TITLE
Error When Publishing Azure DevOps Extension: An item with the same key has already been added

### ISSUE THREAD

**Issue by gattjoe** [microsoft/tfs-cli#353]
Hi,

Platform: OS X
TFS Cross Platform Command Line Interface v0.8.2

After packaging an extension, I receive an error from the Visual Studio Marketplace when I try to update it:

**"An item with the same key has already been added"**

Our Dedicated Support Engineer (DSE) did some advanced troubleshooting on my extension after reproducing the same error and discovered that one of my included files was duplicated in the "Content Types.xml" file. The double entries are:

  **<Override ContentType="inode/x-empty" PartName="/buildAndReleaseTask/python/__init__.py"/>
  <Override ContentType="inode/x-empty" PartName="/buildAndReleaseTask/python/__init__.py"/>**

Shaard from the marketplace gave me the following workaround:

1. Rename the generated VSIX file to .zip file
2. Extract the contents
3. Edit the [Content_Types].xml file removing the extra entry of __init__.py file
4. Package back the contents in a .zip file (make sure that the newly created zip file has same directory structure as the original package, that is no extra nesting of directories).
5. Rename the package extension from .zip to .vsix
6. Upload the package to marketplace

**Comment by kuleshovilya** [comment]
Hello @gattjoe Can this error be reproduced?

**Comment by gattjoe** [comment]
Hi,

I was able to reproduce the error, albeit a different one.  Steps to reproduce:

1. ``` git clone https://github.com/MetLife/TlsTestGate ```
2. add "__init__.py" to TlsTestGate/buildAndReleaseTask/python
3. change the guid so you can publish
4. ```tfx extension create --manifest-globs vss-extension.json```
5. Upload to https://marketplace.visualstudio.com/

I am currently getting the following error: "A token is not valid. Refer to RFC 2616 for correct grammar of content types."

**Comment by kuleshovilya** [comment]
I've tried to do the steps you've described and it worked fine for me, which I guess means that the problem is local, or might be a portal related.
I can recommend try to mail in to portal support, you can find it here:
![image](https://user-images.githubusercontent.com/87485027/131819438-6f51e283-9520-4edc-b985-01bd212e6fb3.png)

Are there any other issues there?

**Comment by gattjoe** [comment]
No, this issue almost had a birthday, but sadly I can no longer reproduce.  I will close.
