### ISSUE TITLE
Alternative installation methods

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/tfs-cli#36]
I don't use npm a lot and was wondering if there are plans to add alternative install methods.

**Comment by yansklyarenko** [comment]
That's a great idea. `choco install tfx` would work best for me! :)

**Comment by bryanmacfarlane** [comment]
It needs npm to install globally.  npm also works across all platforms.  we don't plan on supporting multiple ways of installing - we want one that we can support and document.
