### ISSUE TITLE
tfx extension init fails due to path separator logic

### ISSUE THREAD

**Issue by qodfathr** [microsoft/tfs-cli#363]
In this code: https://github.com/microsoft/tfs-cli/blob/72c0158bfccf9821a5548740c331d057837e3a92/app/exec/extension/init.ts#L242
it is assumed that a path ends with `\`, which works fine on Windows and fails almost everywhere else.

For example, if you `tfx extension init` in WSL, 
```
2020-12-14T18:12:53.189Z : Error: Error unzipping /home/../myextension/azure-devops-extension-sample.zip: Error: EISDIR: illegal operation on a directory, open '/home/.../myextension/'
```
Although the proper way to handle this is to determine the OS path separator, this is a somewhat hacky solution:

```
if (fullPath.endsWith("\\") || fullPath.endsWith("/")) {
```

**Comment by dwilsonactual** [comment]
Fixed in 0.9.0.
