### ISSUE TITLE
Login subcommand issue parsing collection url.

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/tfs-cli#38]
Issue Description: Attempts to pass the unnamed collection URL argument results in the argument being parsed as the authtype argument instead.

Usage info specifies: login \<collection url\> [--authtype <authtype>] [options]

Workarounds: Don't specify the collection URL and let the tool prompt. Also works if pass as a named arg (i.e. --collectionurl \<collection url\>).

Repro Steps:
PS C:\> tfx login http://localhost:8080/tfs/defaultcollection
Copyright Microsoft Corporation

Enter collection url \> http://mymachine:8080/tfs/defaultcollection
Error: Unsupported auth type: http://localhost:8080/tfs/defaultcollection

**Comment by trevorsg** [comment]
Obsolete/fixed with latest release.
