### ISSUE TITLE
How to create a Linux Build Task

### ISSUE THREAD

**Issue by brunodefrancavalli** [microsoft/tfs-cli#383]
Sorry if this was asked before. I could not find documentation about this. If you could point me the right way I would appreciate.

When I run
```
tfx build tasks create
```
Should this be building a task that is OS agnostic? Whenever I try to run the newly create task on a linux agent I get:
```
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
```

What am I missing?

**Comment by jessehouwing** [comment]
Edit the task.json and add a Node and/or Node10 executionhandler (depending on the versions of TFS/Azure DecOps Server) you also want to support. For the latest version of the Azure DevOps (in the cloud), Node10 is the way to go.

Step-by-step explained here:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?WT.mc_id=DOP-MVP-5001511&view=azure-devops&viewFallbackFrom=vsts

**Comment by brunofvalli** [comment]
Thank you. That answer my question
