### ISSUE TITLE
npm audit reports tfx-cli has numerous vulnerable dependencies

### ISSUE THREAD

**Issue by charleszipp** [microsoft/tfs-cli#392]
For my projects that depend on tfx-cli, npm audit will fail due to vulnerable dependencies in tfx-cli. There doesnt appear to be anyway from my projects to resolve these. If I try to run `npm audit fix --force`, npm will revert back to 0.1.11 which also has vulnerabilities. Would it be possible to update the project to not have these vulnerable dependencies so those of us that depend on this dont have these cascade to our projects?

```text
jszip  <3.7.0
Severity: moderate
Prototype Pollution - https://github.com/advisories/GHSA-jg8v-48h5-wgxg
fix available via `npm audit fix --force`
Will install tfx-cli@0.1.11, which is a breaking change
node_modules/jszip
  tfx-cli  >=0.3.0
  Depends on vulnerable versions of azure-devops-node-api
  Depends on vulnerable versions of jszip
  node_modules/tfx-cli

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution in underscore - https://github.com/advisories/GHSA-cf4h-3jhx-xvhq
fix available via `npm audit fix --force`
Will install tfx-cli@0.1.11, which is a breaking change
node_modules/tfx-cli/node_modules/underscore
  azure-devops-node-api  <=10.2.1
  Depends on vulnerable versions of typed-rest-client
  Depends on vulnerable versions of underscore
  node_modules/tfx-cli/node_modules/azure-devops-node-api
    tfx-cli  >=0.3.0
    Depends on vulnerable versions of azure-devops-node-api
    Depends on vulnerable versions of jszip
    node_modules/tfx-cli
  typed-rest-client  <=1.8.3
  Depends on vulnerable versions of underscore
  node_modules/tfx-cli/node_modules/typed-rest-client
```

**Comment by lmmarsano** [comment]
Please update all vulnerable dependencies and stop using outdated packages.
Enterprises with psycho security teams will not allow us build Azure DevOps extensions until these vulnerabilities are cleared.

**Comment by MOlausson** [comment]
Any ETA on when this will fixed? We need it to have a clean dependency audit log when building Azure DevOps extensions.

**Comment by KonstantinTyukalov** [comment]
As far as I know all vulnerable dependencies updated in this PR - https://github.com/microsoft/tfs-cli/pull/410

Let me close this issue then
