### ISSUE TITLE
Task uploaded but not in tasks list or available for build configuration

### ISSUE THREAD

**Issue by veatcha** [Microsoft/tfs-cli#40]
This may be due a lack of understanding on my part, but...

I've used the `tfx build tasks upload` to upload the SqlServerDacpacDeployment task to VSO, which it reported as successful.  When I use the `tfx build tasks list` command though, it doesn't show in the output.  However, if I attempt to upload it again, I get back a 409, which I take as confirmation that the task is already there.

I'm also unable to locate the task in configuring a build definition...any thoughts?

**Comment by bryanmacfarlane** [comment]
SqlServerDacpacDeployment is a task that's in preview hidden behind a feature flag.  If your account isn't enabled you won't see it.  So, you just updated something you can't see.

Finally, the tasks in this repro are open sourced so there's canonical examples of how to write custom tasks.  Master branch here represents code for tasks coded against future product often.  It wasn't open sourced so customers could upload future code into the product now.  For these tasks, you should just wait till they roll out to VSO.

**Comment by roniga** [comment]
If you want to enable SqlServerDacpacDeployment task, please contact RM_Customer_Queries at microsoft dot com as specified in the readme.

**Comment by veatcha** [comment]
@bryanmacfarlane thank you for the insight. @roniga that was my next question - if we could have the feature enabled - thanks!
