### ISSUE TITLE
Release 0.10 missing from this GitHub repo.

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/tfs-cli#403]

**Comment by golubev-ivan** [comment]
Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by golubev-ivan** [comment]
@jessehouwing Do you have any additional questions regarding tfs-cli itself?

**Comment by jessehouwing** [comment]
No. I do not. Just wanted to report that it seems that the release of 0.10 hasn't been added to the GitHub releases section like all other releases.
