### ISSUE TITLE
tfx command line publish issue for Azure DevOps Server 2022 RC1

### ISSUE THREAD

**Issue by Shahyads** [microsoft/tfs-cli#416]
There is a regression bug in tfx-cli for Azure DevOps Server 2022 RC1 see https://github.com/microsoft/tfs-cli/issues/349 

I upgraded our test environment to AzureDevOps 2022 RC1

the release pipeline is defined in my production server (Azure DevOps Server 2020 update1).

it is trying to deploy my extension to a test server (Azure DevOps 2022 RC1) now

I've got the following error message during either the "publish extension" or the "install extension" tasks

error: The given key was not present in the dictionary.

the tfx publish command line doesn't work for Azure DevOps Server 2022 RC1
I tried tfx versions  0.12.0, 0.11.0, 0.10.0, and 0.9.3 and 0.8.3 non of them are working

I can publish and install via Azure DevOps Server 2022RC1 web UI

The version 0.8.3 was working when the test server version was Azure DevOps Server 2020update1

**Comment by vmapetr** [comment]
Hi @Shahyads,
Thanks for your request, we've added this feature request to our backlog. We'll take a look at it once we have enough capacity.

**Comment by ismayilov-ismayil** [comment]
Dear @Shahyads, we didn't receive update, we are closing this issue, feel free to ask any other questions or let us know if it's still relevant for you

**Comment by KubratK** [comment]
Hi @ismayilov-ismayil, I am also having the same issue with this version. Not only the pipeline is not working, but also fails with the command line tfx extension publish

Here is the part of the pipeline:
`npx tfx-cli extension publish^
      --publisher "$(publisher)"^
      --manifest-globs azure-devops-extension.json^
      --overrides-file configs/test.json^
      --override "{\"version\": \"$(ext_version)\"}"^
      --trace-level debug^
      --service-url ${{ parameters.serviceUrl }}^
      --auth-type pat --token ${{ parameters.token }}^
      --trace-level debug^
      --output-path deploy\extension_${{ parameters.mode }}^
      --nowait-validation
  displayName: 'Publish Extension'`


Here is the log:
> 2022-12-12T13:54:13.974Z : -- export-test-protocol-history
> 2022-12-12T13:54:13.974Z : Path 'C:\agents\ABC\_work\1\s\dist\export-test-protocol-history` is a directory. Adding all contained files (recursive).
> 2022-12-12T13:54:13.974Z : -- export-test-protocol-history.html
> 2022-12-12T13:54:13.975Z : -- export-test-protocol-history.js
> 2022-12-12T13:54:13.975Z : -- export-test-protocol-history.js.LICENSE.txt
> 2022-12-12T13:54:13.975Z : -- export-test-protocol-history.js.map
> 2022-12-12T13:54:13.975Z : -- export-test-specification
> 2022-12-12T13:54:13.975Z : Path 'C:\agents\ABC\_work\1\s\dist\export-test-specification` is a directory. Adding all contained files (recursive).
> 2022-12-12T13:54:13.975Z : -- export-test-specification.html
> 2022-12-12T13:54:13.976Z : -- export-test-specification.js
> 2022-12-12T13:54:13.976Z : -- export-test-specification.js.LICENSE.txt
> 2022-12-12T13:54:13.976Z : -- export-test-specification.js.map
> 2022-12-12T13:54:13.976Z : -- organization-settings
> 2022-12-12T13:54:13.976Z : Path 'C:\agents\ABC\_work\1\s\dist\organization-settings` is a directory. Adding all contained files (recursive).
> 2022-12-12T13:54:13.977Z : -- organization-settings.html
> 2022-12-12T13:54:13.977Z : -- organization-settings.js
> 2022-12-12T13:54:13.977Z : -- organization-settings.js.LICENSE.txt
> 2022-12-12T13:54:13.977Z : -- organization-settings.js.map
> 2022-12-12T13:54:13.977Z : -- projectnumber-select-panel
> 2022-12-12T13:54:13.977Z : Path 'C:\agents\ABC\_work\1\s\dist\projectnumber-select-panel` is a directory. Adding all contained files (recursive).
> 2022-12-12T13:54:13.978Z : -- projectnumber-select-panel.html
> 2022-12-12T13:54:13.978Z : -- projectnumber-select-panel.js
> 2022-12-12T13:54:13.978Z : -- projectnumber-select-panel.js.LICENSE.txt
> 2022-12-12T13:54:13.978Z : -- projectnumber-select-panel.js.map
> 2022-12-12T13:54:13.978Z : Path 'C:\agents\ABC\_work\1\s\resources` is a directory. Adding all contained files (recursive).
> 2022-12-12T13:54:13.978Z : -- logo.png
> 2022-12-12T13:54:13.979Z : -- prot-black.png
> 2022-12-12T13:54:13.979Z : -- prot-white.png
> 2022-12-12T13:54:13.979Z : -- spec-black.png
> 2022-12-12T13:54:13.979Z : -- spec-white.png
> 2022-12-12T13:54:13.979Z : -- test-protocol-template.docx
> 2022-12-12T13:54:13.979Z : -- test-specification-template.docx
> 2022-12-12T13:54:13.983Z : Generating [Content_Types].xml

> warning: Could not determine content type for extension .docx. Defaulting to application/octet-stream. To override this, add a contentType property to this file entry in the manifest.

> 2022-12-12T13:54:14.012Z : Found content type for .txt: text/plain.

> 2022-12-12T13:54:14.037Z : Writing vsix to: C:\agents\ABC\_work\1\s\deploy\extension_test\ABC-azure-devops-powertools-test-1.0.157.vsix

> 2022-12-12T13:54:15.127Z : Publishing C:\agents\ABC\_work\1\s\deploy\extension_test\ABC-azure-devops-powertools-test-1.0.157.vsix

> Checking if this extension is already published

> 2022-12-12T13:54:15.131Z : Read vsix as zip... Size (bytes): 3133301

> 2022-12-12T13:54:15.139Z : Files in the zip: ......

> (node:20328) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

> (Use `node --trace-warnings ...` to show where the warning was created)

> It is, update the extension

> error: The given key was not present in the dictionary.

> ##[error]Cmd.exe exited with code '-1'.

> Finishing: Publish Extension
