### ISSUE TITLE
Where build agent with versio 1.88 can be downloaded?

### ISSUE THREAD

**Issue by streamstr** [Microsoft/tfs-cli#43]
Hello everyone.

I'm using on-premise TFS 2015. I've learned about great feature - logging commands (https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md), and wanted to use it in our build process. But when I tried to use it - there was no effect (build number does not changed). Then after googling I found that newer build agent version is needed: https://github.com/Microsoft/vso-agent-tasks/issues/380#issuecomment-146878805

TFS now has 1.83 agents, but I need 1.88.

So, the questions are:
- Is new agent version available for download from somewhere?
- If not, it means, that to get updated agents we need upgrade entire TFS? And we need to wait untill Update 1 is released (but VSO users get their agents updated automatically)?  
- If we need to wait for Update 1, when it will be released?

Thanks.

**Comment by bryanmacfarlane** [comment]
The agent comes from the service.  This command was actually in 1.89 and I believe it just finished rolling out to all scale units yesterday.

Agents (windows) automatically update themselves.  Restart the windows service or use queue admin UI context menu to update all agents.

Since you're usng on-premise 2015, it will come in QU1.  It's in RC1 now and will release soon.

**Comment by mmajcica** [comment]
Hi @bryanmacfarlane 

I have a question related to this one.
I just installed on my TFS2015 the Update 1 RC1. I do see that my newly installed agents are 1.89.0. But how do I upgrade the existing ones?

Thanks

**Comment by chrisrpatterson** [comment]
If you restart the agents the will automatically upgrade of if you look in the pool admin page there is a context menu to force all of the agents to update.

**Comment by mmajcica** [comment]
Hi @chrisrpatterson ,

first thing I tried is to right click on the pool and choose the update all agents options. However it doesn't work for my 1.83.2 agents.
After I execute this command, I do see my 1.89.0 agents restarting, but not the old ones 1.83.2.

Even restarting the service manually doesn't trigger the update.

Any suggestion?

Thanks
