### ISSUE TITLE
tfx-cli, tfx, node

### ISSUE THREAD

**Issue by DynConcepts** [Microsoft/tfs-cli#44]
If I use:

C:\> node tfx-cli <command>....

Things work...

But I can not get things to work if either:
a) I just use "tfx" as shown in all of the samples
b) I am within node

**Comment by bryanmacfarlane** [comment]
If you use npm to install it globally then just use tfx.  When you did the node installer, there's an option to update your paths.  That needs to be done since installing globally on windows creates a .cmd file in a central localtion (which must be in your path).
