### ISSUE TITLE
Agent auto update

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/tfs-cli#49]
Hi,

I just installed the Update 1 RC1 on my on-premise TFS 2015. I was looking for the new build agent version and build tasks. I noticed that the auto-update functionality is not working as expected.

My case:
I have two agents in default pool, one added before the Update 1, version 1.83.2 called Agent1, and one added post Update 1 version 1.89.0 called Agent2.
If I do try to right click the agent pool and choose Update all Agents, I do see my Agent2 going offline (changing color to red) and back online (getting to green). The same is not true for Agent 1. Reported agent one stays the same and it doesn't update.
I tried also restarting the service on my build machine but no luck.
I do see in the agent folder some changes although. There is a folder called agent.old which contains the, what appears, the old version of vsoagent and service executable and worker. I do also see that the windows service running for Agent1 is not pointing to the executable in the agent.old folder, but at the executable in agent folder.
Is this a bug in tfs reporting the wrong version of the agent? How can I get the version of the agent, maybe in my custom build task by reading a value or something similar? 

Thanks

**Comment by ericsciple** [comment]
This works in the new agent, i'm pretty sure it works in the 83 version as well: VsoAgent.exe /version

**Comment by mmajcica** [comment]
Nice one. Thanks

I can confirm that the agent version is 1.89.0

C:\agent1\agent>VsoAgent.exe /version
1.89.0

It means that the reported version is not working as expected.
![screenshot](https://cloud.githubusercontent.com/assets/3026551/10687663/075dc574-796f-11e5-9df5-5f763ec3f1d1.png)

**Comment by mmajcica** [comment]
I do realize only now that this may be not the right place for this discussion.

If interested, I created a connect feedback item in this regards.

https://connect.microsoft.com/VisualStudio/feedback/details/1932246/build-agent-auto-update

Cheers
