### ISSUE TITLE
Attempt to login with server URL succeeds but upload task fails

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/tfs-cli#50]
The login prompt asks for a collection URL, but you can still login if you specify - perhaps accidentally - the server URL instead.

Then when you attempt to upload a task, you get a terrible error message: Cannot read property 'value' of null

For details see: https://github.com/Microsoft/tfs-cli/issues/46 and https://github.com/Microsoft/vso-agent-tasks/issues/593#issuecomment-148762632

**Comment by trevorsg** [comment]
Login now asks for a "service URL", and various commands will try to hit the right host.
