### ISSUE TITLE
bin/tfx is using dos line endings

### ISSUE THREAD

**Issue by halkeye** [Microsoft/tfs-cli#56]
`bin/tfx` is in windows mode
which gives me 
```env: node\r: No such file or directory```
on the mac

I'm not sure if the file is being uploaded to npm or not, but I'm under the impression npm installs it
Using npm:
`2.14.7`

**Comment by trevorsg** [comment]
Working on a fix. Thanks.

**Comment by bryanmacfarlane** [comment]
Note that it doesn't affect what's in npm.  We pushed to npm with a LF after the shebang.

@halkeye - are you saying you were building or you got that after installing from npm

**Comment by halkeye** [comment]
I did an npm install

**Comment by bryanmacfarlane** [comment]
OK - investigating

**Comment by bryanmacfarlane** [comment]
OK - I believe I fixed it.  I just pushed 0.3.1.

**Comment by halkeye** [comment]
:+1: works for me!

**Comment by bryanmacfarlane** [comment]
Great.  Thanks for confirming
