### ISSUE TITLE
tfx extension create - contributions shouldn't be required if item type is "Integration"

### ISSUE THREAD

**Issue by bfcamara** [Microsoft/tfs-cli#57]
For Integration items, which are items that in its manifest specify target `Microsoft.VisualStudio.Services.Integration`, the `extension` commands (`create` or `publish`) shouldn't be requiring at least one contribution.

Integration items can specify only market artifacts (icons, markdowns, etc.) and a Action URL to point to a page explaining how to setup the integration.

**Comment by trevorsg** [comment]
Working on a fix. In the meantime, please use --bypass-validation.

**Comment by trevorsg** [comment]
Fixed.
