### ISSUE TITLE
GitVersion returning different version numbers on local repo vs Build agent repo

### ISSUE THREAD

**Issue by PreetSangha** [Microsoft/tfs-cli#58]
I posted this question on StackOverflow (http://stackoverflow.com/questions/33946642/what-could-make-gitversion-compute-a-different-version-on-the-same-branch-local) and was wonder if you guys could shed any light on how the repos could be different (local = VS 2015 clone, build agent = Build.VNext  clone) - same git version, that would lead to git version not picking up the tag?

Please let me know what other info I can provide. I'm running an on premise TFS 2015 so only have the agents that are in that release and not the ones in the VSO releases.

Thanks.

**Comment by trevorsg** [comment]
I can't tell that this issue is related to tfs-cli in any way. Let me know if I have missed something.

**Comment by PreetSangha** [comment]
I finally worked this out. It was the cache file.
