### ISSUE TITLE
Using in gulp task

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/tfs-cli#59]
I want to build an extension in an gulp task. Is there already a gulp plugin or node module available to build the extension? I see that the tfx utility build on top of `vso-node-api` but it still seems like quite a bit of logic involved in tfx.

**Comment by halkeye** [comment]
I wrote a little script that uploaded all the tasks I had

https://github.com/saucelabs/vso-sauce-ondemand-plugin/blob/master/bin/upload_all.js

Its not the prettiest thing, but does work

**Comment by pascalberger** [comment]
Thanks @halkeye. Where does `tfx-cli/exec/build-tasks-upload` come from? I couldn't find the corresponding code in tfx.

I see that you use vset for creating the extension. This utility seems to be deprecated and replaced with tfx (see https://github.com/Microsoft/vso-extension-tools), therefore I try to achieve the same with tfx.

**Comment by halkeye** [comment]
Yea tfx is rapidly evolving so my code may not work anymore. It was stuff I
used pre launch.

**Comment by trevorsg** [comment]
If you look in app/exec/extension you can find all of the extensions-related logic. Easiest thing to do I think is require app/exec/extension/create and call createExtension() with your mergeSettings and packageSettings. It will handle the rest.

**Comment by trevorsg** [comment]
I'm going to close the issue; let me know if you still need help - trgau@microsoft.com
