### ISSUE TITLE
tfx --version prints wrong version

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/tfs-cli#61]
I just updated to the recently released 0.3.5 version. Globally installed tfx module has version 0.3.5 in its package.json and it also contains the fixes contained in this version.

But if I run tfx --version is still prints 0.3.4. It seems to always be one patch version off (while I had installed 0.3.4 it printed 0.3.3)

**Comment by trevorsg** [comment]
I forgot to re-build after running the build. I found another issue related to versions, so I will fix both in just a sec.

**Comment by trevorsg** [comment]
Fixed/published + tfx-cli@0.3.6

**Comment by trevorsg** [comment]
By the way, it should be "tfx version", not "tfx --version" (although both end up printing the version number, I guess).

**Comment by pascalberger** [comment]
:+1: Thanks!
