### ISSUE TITLE
tfx workitem doesn't have an update sub-command.

### ISSUE THREAD

**Issue by kasajian** [microsoft/tfs-cli#67]
"tfx workitem" has create, query and show, but there's no update.

The "Update work items" section in the REST API includes the following capabilities that should be supported (https://www.visualstudio.com/en-us/integrate/api/wit/work-items)
- Update a field
- Add a tag
- Add / Update / Remove a link
- Add / Remove attachment
- Add a hyperlink

Also allow for "Make an update bypassing rules"

**Comment by trevorsg** [comment]
I will pass this feedback along to the team who owns these commands.

**Comment by kasajian** [comment]
Hello.   I'm curious what the status is on this.  I'm curious if the team feels that this is within the scope of the project or not, and if it is within scope

**Comment by chrisrpatterson** [comment]
It is probably within scope but it is not something we are actively adding.  The primary use case for the CLI is working with extensions and as part of an intern project last summer a few other commands were implemented.  If you want to take a shot at one we could look at a pull request.

**Comment by trevorsg** [comment]
I talked to Matt, who would own this, and he agrees it's within scope, but doesn't have time to work on it now. Unfortunately there's no specific timeline. If you want to take a stab at it, I can help you through the process of adding a new command.

**Comment by mmanela** [comment]
I just merged a change to support this.

**Comment by kasajian** [comment]
Oh nice!   I'll check it out.

**Comment by mmanela** [comment]
FYI: I only added field level updates so far

**Comment by kasajian** [comment]
i have a dumb question.   is the best way to try this to get the commit associated and build locally, or is there a CI build that's available for this commit that can be downloaded?

**Comment by polatengin** [comment]
Since this question is almost 9 years old, and `tfx workitem update --help` is available, I'm closing this issue.

Please feel free to reopen if you think there is a missing functionality.
