### ISSUE TITLE
Under Windows, you can't just type "gulp" to build

### ISSUE THREAD

**Issue by kasajian** [Microsoft/tfs-cli#70]
If you follow the instructions to build the project, it says just to type 'gulp' to build.   That won't work under Windows because the gulp command is in the node_modules\.bin\ folder.

The fix is easy.   Rather than type:

    gulp

instead type:

    npm run gulp

However, this requires that the script section of the package.json file be updated as follows:

BEFORE:

    "scripts": {
      "test": "gulp test",
    },

AFTER:

    "scripts": {
      "test": "gulp test",
      "gulp": "gulp"
    },

**Comment by trevorsg** [comment]
You need to install gulp globally, i.e., npm install -g gulp. Once you do that, simply running gulp from the project root should build the project successfully.

**Comment by kasajian** [comment]
Thank you.   Please update the documentation to indicate.

Also, the fact that gulp is included in the package and installed locally makes it confusing.   Why have it installed as part of the package when it's already required to be installed globally.

**Comment by trevorsg** [comment]
Sure, I can update the docs. I'm not sure why it's set up like that :)
