### ISSUE TITLE
Connection Failed when behind proxy

### ISSUE THREAD

**Issue by cigoliw** [Microsoft/tfs-cli#78]
I'm trying to run the `login` command whilst behind a corporate proxy and I'm getting the error

> Connection failed. Check your internet connection & collection URL.
> Message: connect ECONNREFUSED xxx.xxx.xxx.xxx:443

I've tried both basic and PAT auth but it fails with the same error on both. Trace emits:

> 2016-02-15T13:31:45.639Z : loader.load
> TFS Cross Platform Command Line Interface v0.3.13
> Copyright Microsoft Corporation
> 2016-02-15T13:31:45.830Z : Login.exec
> 2016-02-15T13:31:46.903Z : Connection failed.
> 2016-02-15T13:31:46.907Z : cache.setItem

I suspect that tfx isn't using my proxy. Is it possible to force it to use a specified proxy?

**Comment by trevorsg** [comment]
I'll add an option to specify a proxy server.

**Comment by JPGRodrigues** [comment]
I'm having the same problem.
Is there any workaround?

**Comment by trevorsg** [comment]
Fixed in 0.3.15. Please update by running npm up -g tfx-cli. There is a new option available on all server commands: --proxy. You can use it like this:

`tfx workitem show --work-item-id 42 --proxy "http://myproxyserver:3333"`

**Comment by johnnywell** [comment]
@trevorsg This works with authentication too? Like "http://user:password@myproxyserver:3333" ?

**Comment by gforceg** [comment]
is there a way to specify --proxy <NOTHING> to tell tfs-cli not to use my http_proxy env var? #214
