### ISSUE TITLE
invalid credentials rejection from all urls (http and https)

### ISSUE THREAD

**Issue by grawcho** [Microsoft/tfs-cli#81]
i'm working with on-premise TFS 2015 and am able to create build agents and login to TFX from windows.
from fedora or ubuntu machines i have full access from my browser the server answers to ping nslookup returns the correct server address.
running tfs login --auth-type basic fails (server is configure to accept basic authentication)

  **user@machine ~$ tfx login --auth-type basic
  2016-02-29T14:55:28.712Z : loader.load
  TFS Cross Platform Command Line Interface v0.3.15
  Copyright Microsoft Corporation
  > Service URL: http://serverurl:port/tfs/collection
  2016-02-29T14:55:37.279Z : cache.getItem
  > Username: Domain\Username
  > Password: <correct password> 
  2016-02-29T14:55:53.054Z : Login.exec
  2016-02-29T14:55:53.147Z : Connection failed: invalid credentials.
  2016-02-29T14:55:53.148Z : cache.setItem
  Invalid credentials.
**

I triple checked the credentials and tried accessing with CURL - same result 
BTW - with SSL i have to run** export NODE_TLS_REJECT_UNAUTHORIZED="0"**
otherwise i get:
**Connection failed. Check your internet connection & collection URL.
Message: certificate not trusted**

i really want to pick TFS vNext as my primary cross platform CI system (using TFS since 2012) 
Please advise.

**Comment by grawcho** [comment]
correction ... issue is persistent from windows client as well (checking Network configuration with IT) same machines are able to connect to VSTS instance with PAT and Basic Auth with no issues.

**Comment by elvza** [comment]
Hello grawcho, we just ran into the same thing here at my office.

The reason why it wasn't working for us is because we enabled basic auth at the wrong level in IIS. Instead of enabling it on the application **"Sites/Team Foundation Server/tfs"** we enabled it directly on the site **"/Sites/Team Foundation Server"**. After correcting this oversight it started working as expected.

No restart of the **"Team Foundation Server"** site was required in our case. Hope this helps.

**Comment by grawcho** [comment]
thanks.
i'll try and report back

On Wed, Mar 2, 2016 at 6:00 PM, Elmar Vosloo <notifications@github.com>
wrote:

> Hello grawcho, we just ran into the same thing here at my office.
>
> The reason why it wasn't working for us is because we enabled basic auth
> at the wrong level in IIS. Instead of enabling it on the application *"Sites/Team
> Foundation Server/tfs"* we enabled it directly on the site *"/Sites/Team
> Foundation Server"*. After correcting this oversight it started working
> as expected.
>
> No restart of the *"Team Foundation Server"* site was required in our
> case. Hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/tfs-cli/issues/81#issuecomment-191301588>.
>



-- 
G

**Comment by grawcho** [comment]
just tried ... no luck ... thanks.

On Wed, Mar 2, 2016 at 6:05 PM, shani feldman <grawcho@gmail.com> wrote:

> thanks.
> i'll try and report back
>
> On Wed, Mar 2, 2016 at 6:00 PM, Elmar Vosloo <notifications@github.com>
> wrote:
>
>> Hello grawcho, we just ran into the same thing here at my office.
>>
>> The reason why it wasn't working for us is because we enabled basic auth
>> at the wrong level in IIS. Instead of enabling it on the application *"Sites/Team
>> Foundation Server/tfs"* we enabled it directly on the site *"/Sites/Team
>> Foundation Server"*. After correcting this oversight it started working
>> as expected.
>>
>> No restart of the *"Team Foundation Server"* site was required in our
>> case. Hope this helps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Microsoft/tfs-cli/issues/81#issuecomment-191301588>.
>>
>
>
>
> --
> G
>



-- 
G

**Comment by elvza** [comment]
As an aside the exact display message we got back (stock command prompt), personal details removed and i see one difference, we're using version 0.3.13...:

C:\Program Files (x86)\Microsoft Visual Studio 14.0>tfx login --auth-type basic
TFS Cross Platform Command Line Interface v0.3.13
Copyright Microsoft Corporation
> Service URL: http://<tfs_hostname>:<port>/tfs/collection
> Username: domain\username
> Password: ***
Invalid credentials.

Hope you find an answer soon.

**Comment by grawcho** [comment]
thanks everyone for your inputs.
the issue was: configure basic authentication for iis for entire Team Foundation site,
and logging in to the https://<server>:<port>/tfs  (without collection path)
and logging in with DOMAIN\USERNAME (from command line in Linux needs to add escaping character DOMAIN\\USERNAME)

and the magic happens.

Logged in successfully.

**Comment by grawcho** [comment]
Please Close the issue
