### ISSUE TITLE
`tfx-cli extension install` requires the publisher to be specified even when publishing from VSIX.

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/tfs-cli#90]
Unlike the Share and Publish command, which work without specifying the publisher and extension-id when publishing/sharing from vsix (at least in version 3.13), the new install task throws an error upon installation:

```
2016-03-15T06:31:41.4959398Z ##[debug]C:\TfsData\Build-dev\tasks\ExtensionShareTask\0.0.741\Tools\node_modules\.bin\tfx.cmd extension install --vsix-path C:\TfsData\Build-dev\_work\1\a\vsix\jessehouwing.test-tag-1.1.0.vsix --accounts jessehouwing-dev --no-prompt --json --auth-type pat --token ********
2016-03-15T06:31:41.4969435Z ##[error]Missing required value for argument 'publisher'.
2016-03-15T06:31:41.5019582Z ##[error]Missing required value for argument 'publisher'.
```

I'd expect to be able to install an extension without having to specify the publisher and extensionid.

**Comment by bfcamara** [comment]
Hi @jessehouwing,

it was written with that in mind. The name of the switch to specify the vsix file is `--vsix`. 

Here is an example

```
C:\Projects\vsts-developer-tools>tfx extension install --vsix dist\bfcamara.vsts-developer-tools-build-tasks-0.2.0.vsix --token ******** --accounts bfcamara --no-prompt --json
{
    "itemId": "bfcamara.vsts-developer-tools-build-tasks",
    "accountReports": [
        {
            "itemId": "bfcamara.vsts-developer-tools-build-tasks",
            "accountName": "bfcamara",
            "accountId": "ca4834ae-3761-475c-8fe9-aaf7a7ed5cbb",
            "installed": true,
            "reason": "Extension already installed"
        }
    ]
}
```

Could you try it please?

**Comment by jessehouwing** [comment]
Ohhh now I see... It's my greatest complaint about this tool. Each command uses a slightly different set of parameters... 

Install
Accounts
Vsix

Share
Share with
Vsix path

And in the returning json:

Package
Path

Publish
Packaged

It's making it very hard to guess the right syntax or to apply previous knowledge.

**Comment by bfcamara** [comment]
Yeah, I tend to agree with you @jessehouwing. And from my side, I'm sorry, since it was me that added the `install` command.

I was looking to the share command, and in terms of VSIX it also uses `--vsix`? Are you using `--vsix-path`?

Here is an example 

```
C:\Projects\vsts-developer-tools>tfx extension share --vsix dist\bfcamara.vsts-developer-tools-build-tasks-0.2.0.vsix --token ****** --share-with bfcamara --no-prompt --json
[
    "bfcamara"
]
```

It could be more consistent. Probably It is reflecting that it was written by different people - it shouldn't.

**Comment by jessehouwing** [comment]
I was using - vsix-path, but the next release will switch to the now
unified - vsix.

**Comment by jessehouwing** [comment]
Using `--vsix` fixes the issue. I've updated my extension to use the new format. I'm filing a new issue that tfx-cli doesn't warn me I'm using unrecognized parameters.
